### PR TITLE
THRIFT-2289: Erlang impl of Thrift JSON protocol wrongly writes/expec…

### PR DESCRIPTION
**Pull request by walter-weinmann**
…ts true/false for bools

### CODE REVIEW

**Comment by walter-weinmann** [comment]
This closes #1349

**Comment by walter-weinmann** [comment]
Unfortunately the first step in Travis breaks always with:

`The job exceeded the maximum time limit for jobs, and has been terminated.`

**Comment by walter-weinmann** [comment]
Restarting checks.

**Comment by walter-weinmann** [comment]
Restarting checks.

**Comment by walter-weinmann** [comment]
The checks are really hopeless: Travis fails with maximum time limit and AppVeyor fails with some Haskell problems.

**Sorry I don't know what to do.**

**Comment by walter-weinmann** [comment]
Restarting checks.

**Comment by walter-weinmann** [comment]
Restarting checks.

**Comment by walter-weinmann** [comment]
Restarting checks.

**Comment by walter-weinmann** [comment]
Restarting checks.

**Comment by walter-weinmann** [comment]
Restarting checks.

**Comment by walter-weinmann** [comment]
Restarting checks.

**Comment by walter-weinmann** [comment]
Restarting checks.

**Comment by walter-weinmann** [comment]
Restarting checks.

**Comment by walter-weinmann** [comment]
Restarting checks.

**Comment by walter-weinmann** [comment]
Restarting checks.

**Comment by walter-weinmann** [comment]
Restarting checks.

**Comment by jeking3** [comment]
I recently combined too many cross tests into Job #1.  I have to split one of the protocols (probably binary) out to its own job in order to resolve the timing out cross test.  I'll have a PR submitted for that shortly.  In the meantime please stop making new builds.  I'll let you know when you can rebase.

**Comment by walter-weinmann** [comment]
Waiting for configuration changes in Travis.

**Comment by jeking3** [comment]
Working on it here: #1351 so you can track it.

**Comment by walter-weinmann** [comment]
Problem step 1:
==========

image

Problem step 4:
==========

image

Problem step 11:
===========

image

**Comment by jeking3** [comment]
As I said, working on it here: #1351 so you can track it.  I have item 1 fixed; the others are a haxe issue I didn't see when I did the original docker image refresh and I am looking at it.

**Comment by jeking3** [comment]
hxcpp 3.4.185 was released on 9/11 and it busted haxe builds, probably because it doesn't include static libraries any more.  I will push something soon that should resolve.

**Comment by jeking3** [comment]
If you rebase on master it will help, but I can't guarantee it will make everything clean - will be better.

**Pull request closed without merging**
