### PR TITLE
THRIFT-4825: Aligned the TTlsSocketServerTransport with the TSocketServerTransport

### PR DESCRIPTION
**Pull request by animusblue**
Updated the existing constructor to to use default values for buffering and replaced the simplified constructor with one that allows passing in a TcpListener instance.

- [X] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [X] Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?  (not required for trivial changes)
- [X] Did you squash your changes to a single commit?
- [X] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"

### CODE REVIEW

**Comment by animusblue** [comment]
As pointed out by jeking [here](https://github.com/apache/thrift/pull/1758/files#r265942159), should I have simply created a TcpListener instance in the port only constructor? You wouldn't be able to rethrow an exception as a TTransportException, but is that a requirement?

**Comment by jeking3** [comment]
In these cases I typically refactor the common initialization code to a single method and call that from both constructors.  It avoids future situations where someone modifies one constructor and not the other.  This typically happens when someone adds a variable and then forgets to initialize it in one of the constructors.  Some languages help protect against this, and it's been a while since I did any meaningful C#, so maybe that's not necessary and the compiler catches it?

**Comment by animusblue** [comment]
Unfortunately .NET does not handle this for us. I could, however, pass null to the TcpListener parameter in the chain, and then use the existing code to set the _server value. It would fix the problem.

```csharp
        public TTlsServerSocketTransport(
            int port,
            X509Certificate2 certificate,
            Buffering buffering = Buffering.None,
            RemoteCertificateValidationCallback clientCertValidator = null,
            LocalCertificateSelectionCallback localCertificateSelectionCallback = null,
            SslProtocols sslProtocols = SslProtocols.Tls12)
            : this(null, certificate, buffering, clientCertValidator, localCertificateSelectionCallback, sslProtocols)
        {
            try
            {
                // Create server socket
                _server = new TcpListener(IPAddress.Any, port);
                _server.Server.NoDelay = true;
            }
            catch (Exception)
            {
                _server = null;
                throw new TTransportException($"Could not create ServerSocket on port {port}.");
            }
        }
```

**Comment by jeking3** [comment]
I'd think that you would want to raise an exception if someone passed in a null TcpListener though.  I see what you mean though.  Anyway, it was just a thought.  It doesn't have to be done.  This is still an improvement as-is, I was just thinking about how to consolidate the initialization.

**Comment by Jens-G** [comment]
@jeking3 the Initializer() way would be great, but we will have to sacrifice `readonly` then, since `readonly` vars can conly be set in a CTOR in C#. We could make it an R/O property though.

**Pull request closed without merging**
