### PR TITLE
THRIFT-5265 add the zlib transport to c_glib

### PR DESCRIPTION
**Pull request by zeshuai007**
- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by Jens-G** [comment]
Hi,
(1) whats the status of this?
(2) who could be possibly revieweing this? Its not really a smal change ...
(3) crosstested against some other impl, like c++?

**Comment by zeshuai007** [comment]
@Jens-G I will add crosstested against other impl soon.

**Comment by Jens-G** [comment]
Great!

**Comment by Jens-G** [comment]
Ping

**Comment by Jens-G** [comment]
@zeshuai007 merge?

**Pull request closed without merging**
