### PR TITLE
THRIFT-3999 Fix debian package set up scripts.

### PR DESCRIPTION
**Pull request by matyapiro31**
debian/control: fixing typo and remove innecessary in dependecies.
debina/rules: changing to use cleanup.sh in "clean" target as config.log and config.status remain after make clean.

### CODE REVIEW

**Comment by Jens-G** [comment]
Anyone to confirm this?

**Comment by jfarrell** [comment]
would leave in build-essential, otherwise loks good and +1, @matyapiro31 mind adding build-essential back in

**Comment by jfarrell** [comment]
Thanks for the patch, commit 0c27352

**Comment by matyapiro31** [comment]
@jfarrell , **build-essential** isn't necessary to write in as build-essential is necessary to build whole debian package.  
And also if build-essential is written in debian/control, lintian tells a warning.
So **Must not write build-essential in debian/control**

The error detail is here: https://lintian.debian.org/tags/build-depends-on-build-essential.html

**Pull request closed without merging**
