### PR TITLE
THRIFT-3587 TTLSSocket now supports connect timeout

### PR DESCRIPTION
**Pull request by coeamyd**
Copied code from TSocket.cs to TTLSSocket.cs to support connect timeouts. This fixes issue THRIFT-3587.

### CODE REVIEW

**Comment by coeamyd** [comment]
And heeeere's the pull request :-)

**Comment by jeking3** [comment]
I find it interestingly inefficient to have TTLSSocket **not** deriving from TSocket, otherwise a common method like this timeout handling could be tucked away and reused instead of using code duplication to achieve these means.

**Comment by coeamyd** [comment]
You are absolutely right about this. But, since this is a design decision, I would not want to change this of my own account. The implementation was like this, I just added the missing functionality.

**Comment by jeking3** [comment]
Curious build failure - seems related to a recent commit in lib/csharp, but I thought that passed CI.  @Jens-G did we miss something in #1696?

**Comment by Jens-G** [comment]
Could you rebase and trigger the build again? Should work now.

**Pull request closed without merging**
