### PR TITLE
THRIFT-5217： Deprecated boost header

### PR DESCRIPTION
**Pull request by zeshuai007**
- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by ulidtko** [comment]
Hey! I think you missed some files.

I'd fixed the same warning: https://github.com/apache/thrift/pull/2151/commits/c88fe54f00aef4cd7cb024dda55c1118fb043480

My commit updates 17 files; yours only 11.

**Comment by ulidtko** [comment]
> Hey! I think you missed some files.

Mmm, disregard that. I misread my files counts.

**Comment by ulidtko** [comment]
This PR is ready for merge. @stale undo

**Comment by zeshuai007** [comment]
.

**Comment by emmenlau** [comment]
Thanks @Jens-G !

**Pull request closed without merging**
