### PR TITLE
(CSharp) Adding lifecycle management for service handlers through TProcessorFactory

### PR DESCRIPTION
**Pull request by diogojc**
I want to be able to control the lifecycle of the instances implementing my thrift service handlers (TProcessor).

Before this change the behaviour for every Thrift server is that a service handler will always be the same instance throughout all requests and therefore would either need to be stateless or require thread safety.

I've replaced the TProcessor parameter in the constructors of TServer and subclasses, with a TProcessorFactory so this decision is postponed to the person creating the object graph by specifying a factory for the processors.

Please help me in figuring out what supporting things I need to change to reflect this that I haven't done yet.

Diogo.

### CODE REVIEW

**Comment by Jens-G** [comment]
Nice idea. I'll take a look at it. 

In the meantime, you may want to read our [contribution Guidelines](http://thrift.apache.org/docs/HowToContribute), if you did not do that already.

**Comment by Jens-G** [comment]
I think that's a good addition. But ... I'd like to have it even less breaking. Could you add some more CTORs with the **old** signature? Internally these would just wrap the passed processor into a singleton factory and then call the appropriate new CTOR version. What do you think?

This would automatoically resolve all issues with the tests and the tutorial code that we have right now.

And oh yes, [please create a JIRA issue](http://thrift.apache.org/docs/HowToContribute) for it.

**Comment by Jens-G** [comment]
Hi @diogojc, any news here?

**Comment by jeking3** [comment]
@jfarrell recommend closing this PR.  It was abandoned; no Jira ticket; author's fork has been destroyed.

**Comment by jeking3** [comment]
This pull request is being closed due to lack of activity.  
You can re-open it after rebasing on the current master if you would like it to be reconsidered.

**Pull request closed without merging**
