### PR TITLE
passing exception back to handler for custom use cases

### PR DESCRIPTION
**Pull request by gonthe**

### CODE REVIEW

**Comment by jeking3** [comment]
Hi, thanks for the patch.  I'm cleaning up the PR backlog and found this one.  Could you open a Jira ticket for this?  https://thrift.apache.org/docs/HowToContribute

In addition, if you could resubmit it to run a new CI build, let's see if we can get it to pass.

**Comment by jeking3** [comment]
@gonthe can you rebase on master?

**Comment by jeking3** [comment]
Thank you!  I was running it through local tests after doing same, sadly the unit tests do not pass:
```
Failed examples:

[31mrspec ./spec/processor_spec.rb:43[0m [36m# Processor Thrift::Processor should call process_<message> when it receives that message[0m
[31mrspec ./spec/processor_spec.rb:49[0m [36m# Processor Thrift::Processor should raise an ApplicationException when the received message cannot be processed[0m
[31mrspec ./spec/processor_spec.rb:63[0m [36m# Processor Thrift::Processor should pass args off to the args class[0m
[31mrspec ./spec/processor_spec.rb:73[0m [36m# Processor Thrift::Processor should write out a reply when asked[0m
```

You can get set up to run the unit tests by running the ubuntu-artful docker image (if necessary - if you can build in your linux host directly that's fine too):

`$ ./bootstrap.sh && ./configure && cd compiler/cpp && make -j4 && cd ../../lib/rb && make check`

**Comment by jeking3** [comment]
@gonthe one more chance, if you can fix up the unit test failures this caused, great, otherwise I'm going to close it.  Thanks.

**Comment by gonthe** [comment]
Hi James,
I have changed my company long time ago and we don't use Ruby anymore.

So I have lost the touch with it. Please close the PR. I will get it opened
with working test cases if I ever need it.

Thanks
Mohit

**Pull request closed without merging**
