### PR TITLE
THRIFT-5103: Fix for PHP7.4 deprecated syntax

### PR DESCRIPTION
**Pull request by caspertwo**
- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Review by sveneld — APPROVED** [review]

**Comment by sveneld** [comment]
@Jens-G it's important fix for migrating to php 7.4

**Comment by sveneld** [comment]
@ulidtko please look

**Comment by chriskapp** [comment]
Great, maybe you want also fix this directly at the TCurlClient s.: https://github.com/apache/thrift/blob/master/lib/php/lib/Transport/TCurlClient.php#L102

**Comment by caspertwo** [comment]
Thanks @chriskapp! PR has been updated

**Pull request closed without merging**
