### PR TITLE
THRIFT-4390: Fix bug where binary/buffered messages > 4K could not be read/written

### PR DESCRIPTION
**Pull request by allengeorge**
Client: rs

### CODE REVIEW

**Comment by allengeorge** [comment]
One of two fixes for problems noticed by others during cross-tests. I've a separate PR for framed transports.

**Comment by jeking3** [comment]
There were related cross test errors:
```
===============================================================================
*** Following 3 failures were unexpected ***:
If it is introduced by you, please fix it before submitting the code.
===============================================================================
server-client:          protocol:         transport:               result:
c_glib-rs               multi             buffered-ip              failure(timeout)
c_glib-rs               multic            buffered-ip              failure(timeout)
perl-rs                 multi             buffered-ip              failure(timeout)
```

**Comment by allengeorge** [comment]
@jeking3 This seems like a separate problem unfortunately. I'd removed three tests from the "known failures list" and it appears there's a specific problem related to multiplexed processors and c_glib/perl. That was an oversight :/

I'd suggest the following course of action:

1. I re-add those three test failures to the "known failures" list
2. I fix up the framed test failures with > 4k long messages; I have a patch for this already
3. I add a JIRA for the multiplexed failures and fix that in a separate PR

Let me know if this is acceptable to you, and I'll go about doing that.

**Comment by allengeorge** [comment]
@jeking3 This seems like a separate problem unfortunately. I'd removed three tests from the "known failures list" and it appears there's a specific problem related to multiplexed processors and c_glib/perl. That was an oversight :/

I'd suggest the following course of action:

1. I re-add those three test failures to the "known failures" list
2. I fix up the framed test failures with > 4k long messages; I have a patch for this already
3. I add a JIRA for the multiplexed failures and fix that in a separate PR

Let me know if this is acceptable to you, and I'll go about doing that.

**Comment by jeking3** [comment]
Sure - I like progress. :)

**Comment by allengeorge** [comment]
@jeking3 Thank you!

So...updated the PR to re-add the three failing tests. Created [THRIFT-4451](https://issues.apache.org/jira/browse/THRIFT-4451) to track this. I'm going to fix up the framed transport first, circle back to 4451, and then handle dart/c++ issues.

**Comment by allengeorge** [comment]
@jeking3 Looks like everything passed, so this patch is good to go. TY!

**Pull request closed without merging**
