### PR TITLE
THRIFT-4108 : Fix several problems found on library.

### PR DESCRIPTION
**Pull request by gadLinux**
Adjust headers.
Format code.
Make sure finalization is correct.
Fix convenience methods.
Remove global ssl context.

### CODE REVIEW

**Comment by gadLinux** [comment]
I added also some documentation and missing include functions.

**Comment by gadLinux** [comment]
@jeking3 This was closed but not merged? Why?

**Comment by jeking3** [comment]
It was merged.  Pull master and look at the log.  When your commit is merged into master I have to amend the commit with "This closes #...." which changes the commit hash, so git may tell you when you attempt to delete the branch that it hasn't been fully merged, but it has.

**Comment by Jens-G** [comment]
The careful reader will notice that it says "asfgit closed this in b79396f 19 hours ago". The b79396f is a link to the commit you are looking for.

**Pull request closed without merging**
