### PR TITLE
THRIFT-5079: Check presence of required fields in struct writer

### PR DESCRIPTION
**Pull request by cfriedt**
As of v0.13.0 but probably earlier, and with at least C++, the code generator did not verify that required fields were present on outgoing messages.

This change ensures that the struct writer throws an exception if a required field is not present.

Note, I have not yet added an integration test

  

- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, add ` [skip ci]` at the end of your pull request to free up build resources.

### CODE REVIEW

**Comment by Jens-G** [comment]
> 434 - OptionalRequiredTest (Failed)
Could there be a connection to the patch?

**Comment by dcelasun** [comment]
Thanks for the PR, but this could definitely use some tests.

**Comment by cfriedt** [comment]
> Thanks for the PR, but this could definitely use some tests.
Yes, definitely. It's a WIP.

**Comment by cfriedt** [comment]
> > 434 - OptionalRequiredTest (Failed)
> 
> Could there be a connection to the patch?

Yes. The handling of required fields has changed. I will take a look at that test when I have some time.

**Comment by cfriedt** [comment]
Would like to reopen. I just haven't had time to look at the test case mentioned.

**Comment by Jens-G** [comment]
A rebase seems needed.

**Comment by Jens-G** [comment]
Ping

**Comment by Jens-G** [comment]
@cfriedt This needs a rebase, could you do that?

**Comment by cfriedt** [comment]
In progress

**Comment by cfriedt** [comment]
I should rebase again. So swamped atm

**Comment by cfriedt** [comment]
Rebased.

**Pull request closed without merging**
