### PR TITLE
Thrift 3251 Add http transport for server to Go lib

### PR DESCRIPTION
**Pull request by hhkbp2**
Hi,

This PR is a reopen for previous PR #556, in order to follow the contribute guide.

It adds http transport for server to Go lib.
For more info please refer to Jira
[https://issues.apache.org/jira/browse/THRIFT-3251](https://issues.apache.org/jira/browse/THRIFT-3251)

### CODE REVIEW

**Comment by dimiro1** [comment]
I implemented with a handler func. https://gist.github.com/dimiro1/d38aaf4b7d84c2d5c8f0

**Comment by Jens-G** [comment]
@dimiro1  could you please make a PR out of it?
http://thrift.apache.org/docs/HowToContribute

**Comment by dimiro1** [comment]
@Jens-G The current test infrastructure for the go lib explicitly assume that the server is a SocketServer /test/go/src/server.go. I think it will be a lot of work write the test to conform with the current structure. In my gist [https://gist.github.com/dimiro1/d38aaf4b7d84c2d5c8f0] I wrote a simple test based on a simple Calculator client. What do you think about this approach? Do have any other idea? I am open to suggestions.

**Comment by Jens-G** [comment]
All languages are encouraged 1) to implement the standard Thrift test. This test is the basic test to ensure interoperability across languages for all features implemented. So if we have a http server, that thing should be testable. The [command line syntax is documented](http://thrift.apache.org/test/#test-executable-specification) and works the same way for all languages.

So yes, it would be good to have this integrated into the ThriftTest server and controlled via the ```--transport http(s)``` parameter. The client already supports it, [the server throws an error right now](https://github.com/apache/thrift/blob/master/test/go/src/common/server.go#L92).
____
1) one could also say "required" and it would not be wrong

**Pull request closed without merging**
