### PR TITLE
THRIFT-5152: introduce connect timeout and socket timeout

### PR DESCRIPTION
**Pull request by lvqian**
- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [x] If your change does not involve any code, add ` [skip ci]` at the end of your pull request to free up build resources.

### CODE REVIEW

**Comment by Jens-G** [comment]
CI failed, need to fix
https://travis-ci.org/github/apache/thrift/jobs/667195333?utm_medium=notification&utm_source=github_status

**Comment by lvqian** [comment]
> CI failed, need to fix
> https://travis-ci.org/github/apache/thrift/jobs/667195333?utm_medium=notification&utm_source=github_status

@Jens-G Sorry for the late reply, already fixed CI build.
Please review this mr :)

**Comment by directionless** [comment]
This is a breaking API change. Will it come with a major version bump?

**Comment by dcelasun** [comment]
This change should have been mentioned in [CHANGES.md](https://github.com/apache/thrift/blob/master/CHANGES.md) as it's a breaking change.

@directionless thrift doesn't follow semver and all versions in the form `0.x` are major versions.

**Comment by directionless** [comment]
> thrift doesn't follow semver and all versions in the form 0.x are major versions

That seems unfortunate given how go modules work.

**Comment by dcelasun** [comment]
Well, thrift predates not only Go modules but Go itself so not much we can do here.

**Comment by directionless** [comment]
While thrift itself predates go, the go library certainly does not. It's frustrating to encounter that level of end user hostility from a software project.

**Comment by dcelasun** [comment]
> While thrift itself predates go, the go library certainly does not.

How is that relevant? Thrift supports dozens of languages, most of them predate the go library and they all share version numbers.

> that level of end user hostility

The only hostility I'm seeing here is coming from your end.

**Pull request closed without merging**
