### PR TITLE
THRIFT-4197 [Go] Transparent gzip support for HTTP transport

### PR DESCRIPTION
**Pull request by dcelasun**
Check if the client supports gzip compressed responses and compress the response if it does.

### CODE REVIEW

**Comment by dcelasun** [comment]
Travis failure is unrelated, seems like a Haskell problem:

```
Build log ( /root/.cabal/logs/HUnit-1.6.0.0.log ):
cabal: /root/.cabal/logs/HUnit-1.6.0.0.log: does not exist
lib/hs/CMakeFiles/haskell_library.dir/build.make:88: recipe for target 'lib/hs/thrift_cabal.stamp' failed
make[2]: *** [lib/hs/thrift_cabal.stamp] Error 1
CMakeFiles/Makefile2:3926: recipe for target 'lib/hs/CMakeFiles/haskell_library.dir/all' failed
make[1]: *** [lib/hs/CMakeFiles/haskell_library.dir/all] Error 2
```

**Comment by Jens-G** [comment]
Don't panic, I already planned to look into this. I have a life besidesThrift, you know ;-)

**Comment by dcelasun** [comment]
>  I have a life besides Thrift, you know ;-)

As do we all :)

> Don't panic

No panic here, or in the code! :)

**Comment by mrwiggles** [comment]
Seems very straightforward. Were you able to test it out?

**Comment by dcelasun** [comment]
Yes I did, works just fine.

**Pull request closed without merging**
