### PR TITLE
THRIFT-4529: Rust enum variants are now camel-cased

### PR DESCRIPTION
**Pull request by allengeorge**
Client: rs

### CODE REVIEW

**Comment by allengeorge** [comment]
Build failure caused by a PEBCAK on my part (forgot to change enum variant names in cross-tests). Fixing now.

**Comment by jeking3** [comment]
I assume the default setting is to use the previous way, and this is a new way, so it is backwards compatible?

**Comment by allengeorge** [comment]
I did not include a flag for backwards-compatibility. I'd prefer not to, because this change makes the autogenerated code conform to Rust naming conventions.

**Comment by allengeorge** [comment]
Yes - you're right: it is a breaking change. I'll make the README entries, and make sure I do so for any (hopefully rare!) breaking changes I make in the future. Thank you for catching this.

**Comment by allengeorge** [comment]
I've updated the `CHANGES` file, plus added a `COMPATIBILITY` section to the Rust `README` along with transition guidelines. I will do this in the future for any breaking changes.

**Comment by allengeorge** [comment]
@jeking3 I've made the requested changes, and, the only thing that fails in Travis is the SBCL build under autotools :/ Could this be merged please?

**Pull request merged**
