### PR TITLE
THRIFT-5345: Allow the ServerContext to be Unwrapped Programmatically

### PR DESCRIPTION
**Pull request by belugabehr**
- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [x] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by belugabehr** [comment]
Only C++ stuff failing. Please consider for merge.

**Comment by Jens-G** [comment]
> Please consider for merge.
You can do it yourself, can't you?

**Comment by Jens-G** [comment]
@belugabehr would it be possible to do future PRs from a **forked** repo? 

The way you are doing it adds unwanted extra branches to the main repo. The one for THRIFT 5292 is also still pending. 

While two extra branches are not an real issue, if we are continue going that way we will have very soon 50 extra branches. This is very likely not what everybody wants.

Thank you,.

**Comment by Jens-G** [comment]
+1 LGTM but not tested

**Comment by belugabehr** [comment]
@Jens-G My apologies.  I am no intentionally branching from the Apache Repo.  I will try to be more careful; I will remove these branches.

**Pull request merged**
