### PR TITLE
Fixes THRIFT-2817 and THRIFT-2839

### PR DESCRIPTION
**Pull request by ghost**
Current implementation of json protocols uses buffer peeks extensively.
But in certain situations this causes the buffer to read beyond the json message,
which stalls the whole connection. (THRIFT-2817)

To test this fix I ported the integration tests from the nodejs thrift library to go.
Those are comprehensive integration tests that tests the whole thrift stack.
The tests revealed another problem in TFramedTransport.

When calling TFramedTransport.Read, it should return remaining bytes,
but it doesn't when passing a []byte that is bigger than the current frame_size. (THRIFT-2839)

This PR fixes THRIFT-2817 and THRIFT-2839.

### CODE REVIEW

**Comment by bivas** [comment]
We're still experiencing read errors with this fix merged (`Not enough frame size 4085 to read 4096 bytes`)

The commit is missing a `return` statement in case of `framesize` smaller than the `buffer` and `err == nil ` looks strange

**Comment by Jens-G** [comment]
@bivas Could you provide a PR addressing these issues? Thanks!

**Comment by bivas** [comment]
@Jens-G unfortunately, no. Was pointing this out so maybe @wingedkiwi can have a quick look (and maybe a fix) on this issue.

**Comment by wingedkiwi** [comment]
I'm turning my attention to thrift again in a few weeks. Then I can have a look.

**Pull request closed without merging**
