### PR TITLE
THRIFT-4740:Use std::chrono for timeout and add const to some methods.

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Comment by cyyever** [comment]
> 
> 
> Document breaking changes in language-specific README.md and in top level CHANGES.md files. In this case, all previous time handling public APIs that took integer of milliseconds now take std::chrono, and some methods were changed to const.
> 
> I'd also agree with liberal application of the override keyword throughout the C++ code.

Fixed.

**Comment by cyyever** [comment]
> 
> 
> Document breaking changes in language-specific README.md and in top level CHANGES.md files. In this case, all previous time handling public APIs that took integer of milliseconds now take std::chrono, and some methods were changed to const.
> 
> I'd also agree with liberal application of the override keyword throughout the C++ code.

fixed.

**Comment by jeking3** [comment]
NOTE to self - SQUASH not REBASE

**Comment by jeking3** [comment]
Please rebase on master to clear out CI issues - I just fixed it.

**Comment by cyyever** [comment]
> 
> 
> Please rebase on master to clear out CI issues - I just fixed it.

Done.

**Pull request merged**
