### PR TITLE
THRIFT-4676: Fix intermittent CL build failures

### PR DESCRIPTION
**Pull request by allengeorge**

### CODE REVIEW

**Comment by allengeorge** [comment]
Amazing. Now the CL build is failing with another error, specifically that it doesn't have permissions to write an out file...

**Comment by allengeorge** [comment]
Second try: it appears that executing the builds sequentially doesn't help because the same path is being used for the compiler cache? I think? So I'll try disabling it.

**Comment by allengeorge** [comment]
Going to force push a couple of times to kick off the builds and see if the SBCL error pops up. If it doesn't I can tentatively claim victory.

**Comment by jeking3** [comment]
Shall I merge?

**Comment by allengeorge** [comment]
Yeap. If Tomek would like me to make changes I’m happy to do it in a follow-up PR. The changes as they exist will do the trick for the builds.

**Comment by uint** [comment]
Sorry for taking time. I've looked through it. Looks good to me. Awesome that you cleaned up the makefiles.

If you want to rearrange the directory structure like you've mentioned in the e-mails, I'm good with it! I won't be making any changes here.

Thanks a lot for working on this. Cheers.

**Comment by allengeorge** [comment]
@uint Will do. Thanks so much for taking a look at this!

**Pull request merged**
