### PR TITLE
D lib updated for x64 build mode on windows

### PR DESCRIPTION
**Pull request by Heromyth**
Support for the x64 build mode on windows with DMD 2.074.0 and the latest Libevent

### CODE REVIEW

**Comment by jeking3** [comment]
Looks like this broke unix builds.  As extra credit, if you are able to add D support to the cmake build environment then we can get it to build on appveyor with each pull request, ensuring it won't regress in the future.

**Comment by Heromyth** [comment]
I'll have a try.

**Comment by jeking3** [comment]
This will also need an Apache Jira ticket opened.

https://thrift.apache.org/docs/HowToContribute

**Comment by jeking3** [comment]
@Heromyth any progress on this?

**Comment by Heromyth** [comment]
So sad, there is a bug in phobos64.lib. It will make the examples failed.

**Comment by jeking3** [comment]
This should be rebased on the current master as I have updated the docker files.  Perhaps if you could open a Jira ticket for this issue and rebase on master and force push, we can get a more recent build.

**Comment by Heromyth** [comment]
It's updated by #1380

**Pull request closed without merging**
