### PR TITLE
THRIFT-5490: Use pooled buffer for TFramedTransport

### PR DESCRIPTION
**Pull request by fishy**
Client: go

Follow up on d582a8614, do the same thing on TFramedTransport.

  

- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Review by dcelasun — APPROVED** [review]
LGTM. Apologies for the late review, I was away for a while.

**Comment by fishy** [comment]
> LGTM. Apologies for the late review, I was away for a while.

nah it's ok :) I'm waiting for the year end code freeze to end so we can actually deploy the THeader one to production first anyways.

**Comment by Jens-G** [comment]
>  I'm waiting for the year end code freeze to end

Cold enough it is.

**Comment by fishy** [comment]
The THeader change has been running in our production for one day without issues. Merging this one.

**Comment by fishy** [comment]
Wait I noticed a bug in the TFrameTransport implementation. Fixing now.

**Comment by fishy** [comment]
> Wait I noticed a bug in the TFrameTransport implementation. Fixing now.

I read my pre-holidays code wrong and thought I introduced a bug to break small reads, which turns out to be fine, but I added a test to make sure of it :)

**Pull request merged**
