### PR TITLE
Diverse cmake improvements in dependency handling

### PR DESCRIPTION
**Pull request by emmenlau**
This PR adds a few improvements in cmake dependency handling. Previously, the cmake build did not pass dependencies so well downstream to dependent projects. This PR ensures that all possible dependencies (including thriftz and thriftnb) are passed correctly.

This PR also removes the find-script for libevent. Generally libevent can nowadays often be found with the cmake config. However this may be a breaking change(?)
  

- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [x] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Review by ulidtko — APPROVED** [review]
LGTM (though <code>ThriftConfig<b>.cmake.in</b></code> doesn't look *that good* to me...)

**Review by ulidtko — CHANGES_REQUESTED** [review]
Actually, I think you'll need to bring back the `FindLibevent.cmake` file, @emmenlau. It's not included in [CMake distribution](https://github.com/Kitware/CMake/tree/master/Modules), this will break.

**Comment by emmenlau** [comment]
@ulidtko Yes you are right, I've come to the same thinking. I'm using libevent with cmake, but other people may use it from their distro. Re-added `FindLibevent.cmake`. Please review?

**Review by ulidtko — APPROVED** [review]
Yes sure, LGTM now.

**Comment by emmenlau** [comment]
I've re-added all the support for libevent found via the provided cmake find script, but also added detection for the newer cmake configuration via targets. Basically, cmake should now support libevent in all cases.

Lets see if the CI agrees.

**Comment by emmenlau** [comment]
The Travis CI build errors are from autotools builds and should be unrelated. Please consider for merge.

**Review by zeshuai007 — APPROVED** [review]
LGTM.

**Comment by emmenlau** [comment]
Rebased on latest master. I plan to merge this PR ASAP (if CI remains green against latest master).

**Pull request merged**
