### PR TITLE
THRIFT-4639: Use correct sequence number for multiplexed protocol

### PR DESCRIPTION
**Pull request by phlundblom**
Client: lib/nodejs

### CODE REVIEW

**Comment by phlundblom** [comment]
How does one run the NodeJS tests? Unfortunately I don't find it obvious from the Makefiles and/or the Travis outputs

**Comment by bforbis** [comment]
To run the node tests, follow the instructions in the [docker README](https://github.com/apache/thrift/tree/master/build/docker) for creating your test image.

You can then either run the full test suite with `autotools.sh`, or if you want to just run the nodeJS tests you should be able to run `make check` within the node lib directory. Alternatively, if you understand how grunt files work you can just use that directly.

**Comment by phlundblom** [comment]
I honestly don't have time enough to dig into the the test cases. To me it actually seems like the NodeJS Thrift server implementation in one way or another is broken.

I use NodeJS client against Java multiplexed server and that triggers completely different behaviors. Actually without this patch i get JS errors (`TypeError: this.seqid is not a function`) in NodeJS client rather than just the strange sequence number behaviors that appears when running unit tests against NodeJS server.

**Comment by jeking3** [comment]
Author indicated insufficient time to complete the PR, and the changes don't appear to actually change anything other than a variable name.  In addition the tests did not pass.  This will be closed in favor of THRIFT-4405 verifying correctness.

**Comment by jeking3** [comment]
Reopened, will shepherd this through.

**Comment by jeking3** [comment]
I rebased on master to fix up CI issues, if they are not caused by the patch.

**Comment by jeking3** [comment]
I was able to use local changes in THRIFT-4780 to prove this is not necessary; nodejs is sending sequence numbers just fine.

**Pull request closed without merging**
