### PR TITLE
Travis star repo feature test

### PR DESCRIPTION
**Pull request by muizzk**
- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [ ] Did you squash your changes to a single commit?  (not required, but preferred)
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by Jens-G** [comment]
WF?

**Comment by ulidtko** [comment]
@muizzk hey, did you get it working?

This is what Travis Support has told me (utter BS as usual):
> Unfortunately if you do not have push access to a repo you will not be able to find the repo on your dashboard and will also not be able to "star" the repo.
> After you gain "push" access you will be able to star the repo.

@Jens-G it's pretty laborious to navigate to apache/thrift project on Travis, should be a 1-click thing but isn't... I was trying, I guess just like @muizzk, to "follow" it in any way so that it appears on the dashboard. [This blog][•] says it's possible to "star" projects somehow — I still don't see how — and their tech support is insistently feeding me nonsense.

[•]: https://blog.travis-ci.com/2017-02-28-introducing-dashboard

**Comment by muizzk** [comment]
> @muizzk hey, did you get it working?

@ulidtko yes, I did. See screenshots below

Screenshot 2020-10-14 at 3 52 14 PM


To quote from the blog:

> The Dashboard is a new way to interact with Travis CI. It’s your personal, central starting point where you see all of the repositories you have access to at a glance.

I created a fork of the repo (_which gave me push access to my fork_) and was subsequently able to star the repo in my dashboard. I hope this helps.

**Comment by ulidtko** [comment]
OMG I feel so dumb right now. @muizzk thanks a lot for the screenshot, now I finally see the star, and it works!

**Comment by Jens-G** [comment]
>> WTF?
> @Jens-G [some lengthy explanation]
Yeah, that's why there is a huge comment field to fill in when you open a pull request. So every body knows what this is about :-) To me it looked just like one of these every-now-and-then popping up nonsense PRs, so I closed it.

**Pull request closed without merging**
