### PR TITLE
Fix generated Node JS code

### PR DESCRIPTION
**Pull request by bracki**
As reported in https://issues.apache.org/jira/browse/THRIFT-1840 and https://issues.apache.org/jira/browse/THRIFT-2527 the generated JS code pollutes the global namespace because it lacks `var` keywords.

This PR adds the `var` keyword where appropriate.
It also appends missing `;`, thus making tools like [jshint](http://jshint.com/) et. al. happier.

### CODE REVIEW

**Comment by cjthompson** [comment]
Looking at this change, I believe this will break namespacing because the output will be invalid JavaScript:

````javascript
var Namespace.Object.Type = {}
````

For namespacing to work, the namespace object would have to be declared at the top of the file and the `var` keyword not used when adding to the namespace object.

**Comment by bracki** [comment]
@cjthompson Good catch! I haven't tried out using `js` namespaces.

What are they good for anyways? Wouldn't you define your namespace when requiring the files?

**Comment by cjthompson** [comment]
I don't use the javascript namespaces either.  With the globals fixed, I just do a require of the file where it's needed.  So you might need to change the code to only output the var if `js_namespace()` return an empty value.

**Comment by timse** [comment]
any news on this? would that change do the job @cjthompson?

**Comment by cjthompson** [comment]
I'm not a C developer, but at first glance it looks like it might work. Let's see if anyone from the apache foundation agrees to merge it.

**Comment by nsuke** [comment]
Would you fix this error ?
https://travis-ci.org/apache/thrift/jobs/92427337#L1307

**Comment by timse** [comment]
there were a couple of syntax errors so i allowed myself to force push fix them
should be fixed now @nsuke

**Comment by nsuke** [comment]
Committed, thank you folks !

**Pull request closed without merging**
