### PR TITLE
export thrift::mem::TBufferTransport

### PR DESCRIPTION
**Pull request by flier**
We need export `thrift::mem::TBufferTransport` to serialize record to a memory based buffer, then send the buffer through other transport like Kafka

### CODE REVIEW

**Comment by sunchao** [comment]
I created a ticket for this: THRIFT-4113. However, a easy workaround is to just create a wrapper around the memory buffer, and implement Read + Write yourself.

**Comment by flier** [comment]
Thanks, we use open source project because we are not intent to reinvent wheel :)

**Comment by jeking3** [comment]
Please rebase against upstream/master and force push to kick a new build.  I'd like to see CI pass (or get much closer) before merging.

**Comment by sunchao** [comment]
This change looks good to me, even though I'm also relatively new to Rust.

**Pull request closed without merging**
