### PR TITLE
update TSocket.php

### PR DESCRIPTION
**Pull request by lihanharry**
- add connect timeout
- support accurate send timeout and write timeout

### CODE REVIEW

**Comment by lihanharry** [comment]
sorry there is something wrong with the codestyle,I will modify and give another pull request

**Comment by jeking3** [comment]
THRIFT-4171

**Comment by jeking3** [comment]
@lihanharry would it be possible for you to rebase this on the current upstream master and resubmit it?

**Comment by jeking3** [comment]
@lihanharry would it be possible for you to rebase this on the current upstream master and resubmit it?

**Comment by lihanharry** [comment]
Sorry to miss this mail. 
I'll rebase it this weekend, Thank you for your reminding





At 2017-10-25 22:15:25, "James E. King, III" <notifications@github.com> wrote:


@lihanharry would it be possible for you to rebase this on the current upstream master and resubmit it?

**Comment by jeking3** [comment]
@lihanharry I tried to rebase it but it was not trivial, so I would like you do to it if you have time.

**Comment by jeking3** [comment]
@lihanharry please move this forward or it will eventually be closed due to inactivity.  @RobberPhex any concerns with this code?

**Comment by jeking3** [comment]
@lihanharry please move this forward or it will eventually be closed due to inactivity. @RobberPhex any concerns with this code?

**Pull request closed without merging**
