### PR TITLE
THRIFT-5377 Remove Erlang R16 support

### PR DESCRIPTION
**Pull request by kpy3**
Erlang R16 has reached end of life several years ago

  

- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by Jens-G** [comment]
Again? Remove twice?

**Comment by kpy3** [comment]
> Again? Remove twice? In case you didn't notice, the previous PR #2354 got merged.

Oh, sorry missed that! I've found I forgot to cleanup `configure.ac`, help in generator and test and decided to update my open PR. Should I create another PR for that?

**Comment by Jens-G** [comment]
> Should I create another PR for that?

I see, no leave it as it is. I'll look at it as soon as I have the time.

**Comment by Jens-G** [comment]
Removed last leftover in configure.ac, then merged.

**Pull request closed without merging**
