### PR TITLE
THRIFT-5760 Update minimal version of php

### PR DESCRIPTION
**Pull request by sveneld**
Update minimal version of php to 7.1

I know that currently 8.* is main version, but current code has to much dependencies on version 5, so let's move step by step.

- [X] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket? https://issues.apache.org/jira/browse/THRIFT-5760
- [X] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [X] Did you squash your changes to a single commit?  (not required, but preferred)
- [X] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by sveneld** [comment]
@pkvach

**Comment by pkvach** [comment]
@sveneld 
I noticed a few more places in the documentation where PHP 5 is mentioned. 
Could you please update those as well?
https://github.com/apache/thrift/blob/3b1c30c5a7fd4f0142ef93bb6e0221e4a69dcf12/lib/php/README.md?plain=1#L24
https://github.com/apache/thrift/blob/3b1c30c5a7fd4f0142ef93bb6e0221e4a69dcf12/doc/install/README.md?plain=1#L35

**Comment by sveneld** [comment]
Thank you, I missed it.
Pull request is updated

**Comment by pkvach** [comment]
LGTM, thank you

**Comment by sveneld** [comment]
@Jens-G let's merge this pull request

**Pull request merged**
