### PR TITLE
THRIFT-3916 Throw proper errors from JS, not strings

### PR DESCRIPTION
**Pull request by SimenB**
I'd love to add a test for this, but I can't find where to do that.

EDIT: I'm unable to get bison to register correctly in order to run the tests locally (Mac).

Is there some Dockerfile I could use that installs dependencies and an elegant way for me to run the tests?

### CODE REVIEW

**Comment by nsuke** [comment]
@SimenB we have `Dokerfile` s for build env inside build/docker/ subdirectories.
You can also do `docker pull thrift/ubuntu` or thrift/debian.

**Comment by jeking3** [comment]
@SimenB if you are interested in resurrecting this let me know - rebase on current master and push to CI will run all our tests.

**Comment by jeking3** [comment]
@SimenB if you are interested in resurrecting this let me know - rebase on current master and push to CI will run all our tests.

**Comment by jeking3** [comment]
@bananer is this worth pulling forward if it passes a build?  Is it a breaking change?

**Comment by bananer** [comment]
@jeking3 This is a well-intended change but I think it is not implemented correctly and will break error handling for users.

In some places in the compiler the input to `render_recv_throw` already is a proper `Error` (the JS exception class), e.g. https://github.com/apache/thrift/blob/2b09dfed9c6b858571e7d8829a2b4a4bcda18d6a/compiler/cpp/src/thrift/generate/t_js_generator.cc#L1648-L1652

This is not the case for other places:
https://github.com/apache/thrift/blob/2b09dfed9c6b858571e7d8829a2b4a4bcda18d6a/compiler/cpp/src/thrift/generate/t_js_generator.cc#L1673

The proper way of doing this would be to inspect all usages of `render_recv_throw` to see if the argument needs to be wrapped in `new Error(…)`. Still then, this could break error handling that relies on these cases being strings.

**Comment by jeking3** [comment]
Original author has not responded to any comments and PR needs more work.  Closing the PR.

**Pull request closed without merging**
