### PR TITLE
THRIFT-4222: Add Golang NewTServerSocketFromAddrTimeout

### PR DESCRIPTION
**Pull request by zwass**
Adds the ability to create a new server socket from a non-TCP (eg. Unix socket)
address. Modeled after the existing NewTSocketFromAddrTimeout function.

### CODE REVIEW

**Comment by zwass** [comment]
Note that this obviates the need for a library like https://github.com/Wang/thrift_unix_domain/blob/master/server_unix_domain.go, which is mostly a copy of the existing implementation with a minor change to support unix domain socket addresses.

**Comment by zwass** [comment]
I don't think any of the test failures are related. Please let me know if this needs anything else to be merged.

**Comment by Jens-G** [comment]
If you could file a JIRA ticket, that would be awesome :-)
http://thrift.apache.org/docs/HowToContribute

**Comment by zwass** [comment]
JIRA ticket filed: https://issues.apache.org/jira/browse/THRIFT-4222

**Comment by Jens-G** [comment]
Ok, I'll look at it.

**Pull request closed without merging**
