### PR TITLE
Replace git.apache.org imports with github.com

### PR DESCRIPTION
**Pull request by dcelasun**
Github has been the canonical repo for a while now and I plan to merge this before 0.12 is tagged. I'm opening a PR to see if anyone has any feedback.

If you think this should be reverted or delayed, please say so.

### CODE REVIEW

**Comment by jeking3** [comment]
@jfarrell this should be pulled into 0.12.0.

**Comment by dcelasun** [comment]
@jeking3 I don't think this is related to THRIFT-4652?

**Comment by jeking3** [comment]
Apologies!

**Comment by dcelasun** [comment]
No worries, reverting title. I could use your input on THRIFT-4652 by the way.

**Comment by craigem** [comment]
FYI: [git.apache.org](https://git.apache.org/) is now down and [not expected up](https://blogs.apache.org/infra/entry/subversion-to-git-service-git) any time soon, if ever:

Attempts build software with a thrift dependency now end up with errors like this:

```
s/* in /home/craige/go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:                                   
        fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out                      
go: error loading module requirements
``

If there was a time to change the canonical source, I would put now forward as a suggestion :-)

**Pull request merged**
