### PR TITLE
THRIFT-3405

### PR DESCRIPTION
**Pull request by justonia**
Implementation for THttpClient as referenced by:

https://issues.apache.org/jira/browse/THRIFT-3405

Some lines within the RemainingBytes() method were changed as a result of running go fmt and are unrelated to the issue above.

### CODE REVIEW

**Comment by justonia** [comment]
I also forgot to mention that all changes are additive and do not change the existing public API.

**Comment by justonia** [comment]
The CI failure does not seem related to my changes...

**Comment by Jens-G** [comment]
Committed per 13ac77daf031443ebdfbee02bad528f53b6212eb, this can be closed.

**Comment by jeking3** [comment]
@jfarrell this can be closed - it was merged.

**Pull request closed without merging**
