### PR TITLE
Fix cpp header issues

### PR DESCRIPTION
**Pull request by cfriedt**
2 commits to address 2 issues:
* lib: cpp: transport: include thrift/config.h in TFDTransport
  - Fixes https://app.travis-ci.com/github/apache/thrift/jobs/589120685
* lib: cpp: automake: ship thrift/numeric_cast.h
  - Fixes https://app.travis-ci.com/github/apache/thrift/jobs/589120686

cc @Jens-G

### CODE REVIEW

**Comment by Jens-G** [comment]
I merged it because it changes the situation to the better. However I would say there is sth else:
https://app.travis-ci.com/github/apache/thrift/jobs/589165720
https://app.travis-ci.com/github/apache/thrift/jobs/589165723

The c_glib tests use a C++ server to test against. Seems there are some adjustments needed too, because now it complains about missing sleep(), fork() and throw()

**Comment by Jens-G** [comment]
@cfriedt : Thoughts?

**Comment by cfriedt** [comment]
> I merged it because it changes the situation to the better. However I would say there is sth else:
> https://app.travis-ci.com/github/apache/thrift/jobs/589165720
> https://app.travis-ci.com/github/apache/thrift/jobs/589165723
> 
> The c_glib tests use a C++ server to test against. Seems there are some adjustments needed too, because now it complains about missing sleep(), fork() and throw()
> 

@Jens-G - I noticed that as well. Shall I put together a fix for c_glib? I'm not sure yet what the root cause is yet.

(Sorry for the late response, i had left my comment in draft by accident)

**Comment by Jens-G** [comment]
That would be super awesome.

**Pull request merged**
