### PR TITLE
THRIFT-3887: adding factories to the generated Java classes

### PR DESCRIPTION
**Pull request by korovkin**
adding factories to the generated Java classes, allowing the user to control the type of classes to be allocated when de-serializing the incoming message.

example of generated code:

```
public class Team implements ... {

  ...
  public static class TeamFactory {
    public Team allocate() { return new Team(); }
    public Team allocate(Team other) { return new Team(other); }
    public Team allocate(String teamId, String name, String domain, String email_domain, String plan) { return new Team(teamId, name, domain, email_domain, plan); }
  }

  public static volatile TeamFactory factory = new TeamFactory();
  public static void setFactory(TeamFactory f) { factory = f;}
  public static TeamFactory getFactory() { return factory;}

  ...
}
```

### CODE REVIEW

**Comment by korovkin** [comment]
contributing back from slackhq

**Comment by korovkin** [comment]
CC: @smourachov

**Comment by Jens-G** [comment]
Hi @korovkin, thanks! Could you please create a matching JIRA ticket for it, according to our [contrib guidelines](https://thrift.apache.or/docs/HowToContribute)?

**Comment by korovkin** [comment]
sure. 
added: https://issues.apache.org/jira/browse/THRIFT-3887

**Comment by jeking3** [comment]
This needs to be rebased on the current master and resubmitted; we need a clean CI build before we can proceed.

**Comment by jeking3** [comment]
This needs to be rebased on the current master and resubmitted; we need a clean CI build before we can proceed.

**Comment by jeking3** [comment]
Please change the destination to master, and rebase on master so we can get a fresh CI build in order for this to proceed.  Thanks.

**Comment by jeking3** [comment]
Would also prefer to see a test exercising the new code.

**Comment by korovkin** [comment]
we are no longer using this approach, safe to close

**Pull request closed without merging**
