### PR TITLE
THRIFT-2790 thrift -gen all => an option to generate all languages an…

### PR DESCRIPTION
**Pull request by bufferoverflow**
…d features

### CODE REVIEW

**Comment by jeking3** [comment]
This would be useful in the static code analysis build to generate all language files.  Any chance you can rebase this, or if no longer wanted, close this PR and the Jira ticket that drove it?

**Comment by Jens-G** [comment]
This will not generate nodejs code, to name just one case.

**Comment by jeking3** [comment]
Should this be moved forward or closed?

**Comment by jeking3** [comment]
Should this be moved forward or closed?

**Comment by jeking3** [comment]
@bufferoverflow Should this be moved forward or closed?

**Pull request closed without merging**
