### PR TITLE
Update language levels, fix erlang and rust in CI

### PR DESCRIPTION
**Pull request by jeking3**
- Include rebar3 in docker image so erlang builds in CI
- Include the correct path in docker image so rust builds in CI
- Updated common lisp (sbcl) to 1.5.3 in docker image
- Updated dlang to 2.086.1 in docker image
- Updated dart to 2.4.0 in docker image
- Updated erlang to 22.0 in docker image
- Updated openjdk to 11.0.3 in docker image
- Updated node.js to 10.16 in docker image
- Updated rust to 1.35.0 in docker image

  

- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?  (not required for trivial changes)
- [x] Did you squash your changes to a single commit?
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"

### CODE REVIEW

**Comment by allengeorge** [comment]
@jeking3 Sorry for the delay. I'm trying to fix the rust tutorial build failures right now, and I'll try to fix the rust build specifically so that we use a pinned version of rustc as opposed to whatever's on stable at the time the docker container is built.

**Comment by jeking3** [comment]
Issue reproduced locally (gotta love docker containers)... looking into it.

**Comment by jeking3** [comment]
Now the erlang feature test for TLS is breaking.  See what happens when a language rots because it's not being built?

**Comment by jeking3** [comment]
So erlang 22 includes erlang ssl 9.3 which disables TLS 1.0 and 1.1 by default, but TLSv1.2 doesn't seem to be working either.  I'll have to back down to erlang 21 for now unless someone with some erlang knowledge can fix the TLS feature test.

**Comment by jeking3** [comment]
The dlang unit test async_test is failing for ssl and hanging causing those builds to fail.  This seems to be related to the newer version of dlang in use.  I had upgraded from 2.083 to 2.086.  I'll try to bisect it.

**Comment by jeking3** [comment]
One last thing to take care of, the Xenial Dockerfile isn't working on install of cabal.

**Comment by jeking3** [comment]
The issue with the Xenial build is (hopefully) a server error on the haskell server side.  As such, I'm going to merge this.

**Pull request merged**
