### PR TITLE
netstd: Log errors in processor via standard logger 

### PR DESCRIPTION
**Pull request by cspwizard**
netstd: Log errors in processor via standard logger 

  - [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by Jens-G** [comment]
I made the logger optional to a) not break existing code (including the Test suite) and b) not to force people into using it.

**Comment by cspwizard** [comment]
I may miss the idea, but how is it optional when there is an output directly to console?

**Comment by Jens-G** [comment]
Main reason for the change was that you added the logger argument in a way that broke existing code. You could have easily recognised this yourself just by trying to build the code we have. Since logging is a non-mission critical task to Thrift the very obvious solution was to make the argument option by adding `= default` and of course take care of that case when the logger is used. That way you are free to provide a logger but are not forced to do it, in which case it simply behaves as before. I'd consider this as the optimum solution. Whether or not someone is using docker or not is of no relevance here.

**Comment by cspwizard** [comment]
Ah, ok. I'll change the code. 
My point was that the logger/console in current implementation is not optional in any way. It just prints unformatted text to a console and that brings some problems in use

**Comment by Jens-G** [comment]
I already merged you PR, in case you did'nt notice. Further PRs welcome of course.

**Comment by cspwizard** [comment]
Great, thanks

**Pull request closed without merging**
