### PR TITLE
THRIFT-4661: Rust enum name wrong case in generated structs

### PR DESCRIPTION
**Pull request by jake-ruyi**
Client: rs

Small fix with test.

### CODE REVIEW

**Comment by allengeorge** [comment]
@jake-ruyi Thank you for the bug report and the PR! The changes look good.

**Comment by allengeorge** [comment]
@jeking3 The build failures appear to be unrelated.

On Appveyor it looks like JDK8 could not be downloaded/unpackaged (?) and on Travis it looks like the CL compile failed because it couldn't find a generated thrift file (I wonder if there's some sort of Makefile bug or race; lemme look into that).

Could this be merged?

**Comment by jeking3** [comment]
@allengeorge do you have access in GitHub to "approve" a PR?  If you go to the "Files changed" tab, can you submit a review approval from there?  I'm just curious.

**Comment by jeking3** [comment]
On the CL missing file my assumption was it is a race inside the cl build framework.  It has plagued the project since CL was added.  If you can smite that, it would help stabilize the builds.  The other issue I have seen is a less frequent ssl/socket issue in the dlang tests.

**Comment by allengeorge** [comment]
@jeking3 I can approve (just did), but I don't have write access to the repo, so I can't actually merge PRs.

**Pull request merged**
