### PR TITLE
THRIFT-4064: update node dependencies

### PR DESCRIPTION
**Pull request by jeking3**

### CODE REVIEW

**Comment by jeking3** [comment]
I don't get this...
```
Running "jsdoc:dist" (jsdoc) task
>> fs.js:1919
>>   binding.copyFile(src, dest, flags);
>>           ^
>> 
>> Error: EISDIR: illegal operation on a directory, copyfile '/thrift/src/lib/js/node_modules/jsdoc/templates/default/static/fonts/OpenSans-Bold-webfont.eot' -> 'doc/fonts'
>>     at Object.fs.copyFileSync (fs.js:1919:11)
>>     at /thrift/src/lib/js/node_modules/jsdoc/templates/default/publish.js:471:12
>>     at Array.forEach (<anonymous>)
>>     at Object.exports.publish (/thrift/src/lib/js/node_modules/jsdoc/templates/default/publish.js:468:17)
>>     at Object.module.exports.cli.generateDocs (/thrift/src/lib/js/node_modules/jsdoc/cli.js:430:39)
>>     at Object.module.exports.cli.processParseResults (/thrift/src/lib/js/node_modules/jsdoc/cli.js:383:20)
>>     at module.exports.cli.main (/thrift/src/lib/js/node_modules/jsdoc/cli.js:227:14)
>>     at Object.module.exports.cli.runCommand (/thrift/src/lib/js/node_modules/jsdoc/cli.js:180:5)
>>     at /thrift/src/lib/js/node_modules/jsdoc/jsdoc.js:103:9
>>     at Object.<anonymous> (/thrift/src/lib/js/node_modules/jsdoc/jsdoc.js:104:3)
>>     at Module._compile (module.js:624:30)
>>     at Object.Module._extensions..js (module.js:635:10)
>>     at Module.load (module.js:545:32)
>>     at tryModuleLoad (module.js:508:12)
>>     at Function.Module._load (module.js:500:3)
>>     at Function.Module.runMain (module.js:665:10)
```

I even tried using a "mkdir -p doc/fonts" before running the grunt command in the makefile in case doc/fonts is a file.  I haven't been able to reproduce this elsewhere; I'm going to start with a clean git clone and checkout this branch.  This error is present in all the recent builds, especially on job 4 which runs all the unit tests.

**Comment by jeking3** [comment]
@Jens-G any ideas on how to deal with this?  I've been working on it for a full day now and I cannot reproduce it using a fresh docker image and a fresh clone of the repo, but it fails inside travis every time.  My only recourse would be to disable the language until someone can figure it out.

**Comment by jeking3** [comment]
I found grunt-jsdoc had a recent update; I changed the lib/js packages.json to require the 2.1.1 version or later, as they had a dependency issue with other packages that popped up.  When I ran npm install, it downrevved jsdoc from 3.5.4 to 3.4.3.  Let's see if that makes a difference.

**Comment by jeking3** [comment]
Well that didn't work either.

**Comment by nsuke** [comment]
jsdoc 3.5.5 addresses the issue: https://github.com/jsdoc3/jsdoc/issues/1438
From what I see there, you would need to rebuild the node installation layer of your local docker image to reproduce the issue, by e.g. `docker build --no-cache`

**Pull request closed without merging**
