### PR TITLE
THRIFT-4273 erlang:now/0: Deprecated BIF.

### PR DESCRIPTION
**Pull request by walter-weinmann**
Simply following the recommendations here:

[3.7  New Time API](http://erlang.org/doc/apps/erts/time_correction.html#id79939): How to Work with the New API

### CODE REVIEW

**Comment by walter-weinmann** [comment]
This closes #1346

**Comment by walter-weinmann** [comment]
Restart checks.

**Comment by walter-weinmann** [comment]
Restarting the checks.

**Comment by walter-weinmann** [comment]
Restarting the checks.

**Comment by walter-weinmann** [comment]
Restarting the checks.

**Comment by walter-weinmann** [comment]
Restarting the checks.

**Comment by walter-weinmann** [comment]
The checks are really tedious - I needed 5 attempts until everything had gone through without any problems.

**Comment by jeking3** [comment]
@walter-weinmann what was failing - Appveyor or Travis?  There are some known build issues lurking about.  I just eliminated one that popped up occasionally with concurrency_test in C++, however I just found that on Appveyor haskell is failing dependency checks sometimes.

**Comment by jeking3** [comment]
What versions of Erlang would this change eliminate as usable with Thrift?  I am finding it hard to locate the erlang release where the timestamp method was introduced.

**Comment by walter-weinmann** [comment]
The problems were with Travis with varying reasons. I think it would be interesting to look into it. There may be a couple of pull request with bad results in Travis based on Travis internal problems. Similar observations  wit Appveyor - is it really useful to run both ?

**Comment by walter-weinmann** [comment]
The `erlang:timestamp/0` method seems to be a very old kernel methods - from the [release notes](http://erlang.org/doc/apps/kernel/notes.html) (current kernel release is 5.3):

> 1.42  Kernel 2.13.2
> 
> Fixed Bugs and Malfunctions
> 
> A bug when doing io:get_line (among other calls) from a file opened with encoding other than latin1, causing false unicode errors to occur, is now corrected.
> 
> Own Id: OTP-7974
> 
> Improvements and New Features
> 
> Added functionality to get higher resolution timestamp from system. The erlang:now function returns a timestamp that's not always consistent with the actual operating system time (due to resilience against large time changes in the operating system). The function os:timestamp/0 is added to get a similar timestamp as the one being returned by erlang:now, but untouched by Erlangs time correcting and smoothing algorithms. The timestamp returned by os:timestamp is always consistent with the operating systems view of time, like the calendar functions for getting wall clock time, but with higher resolution. Example of usage can be found in the os manual page.
> 
> Own Id: OTP-7971

**Comment by jeking3** [comment]
Building Appveyor right now probably not, since I don't think we do erlang on windows in our CI right now.  In order to get there, we need erlang support in the cmake build environment.  The travis builds are the important ones, although as we discovered with the tutorials rotting, a build is only as good as what it tests.  Hopefully we have enough tests to cover these changes.

**Comment by walter-weinmann** [comment]
@jeking3 please have a look at THRIFT-2289 and THRIFT-2889 - I suppose both can be closed.

**Comment by NOMORECOFFEE** [comment]
Hi, @walter-weinmann. This's patch #1000 do the same thing. :wink:

**Pull request closed without merging**
