### PR TITLE
Gracefully handle EOF for Rust TProcessors

### PR DESCRIPTION
**Pull request by sadroeck**
Gracefully terminated thrift connections for thrift server implementations in Rust would still show a `WARN` log message, as the `handle_incoming_connection` loop does not distinguish between proper transport layer errors and EOF. This pull request will allow EOF transport errors to gracefully close the RPC call.

- [X] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes) --> N/A
- [X] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [X] Did you squash your changes to a single commit?  (not required, but preferred)
- [X] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [X] If your change does not involve any code, add ` [skip ci]` at the end of your pull request to free up build resources.

### CODE REVIEW

**Comment by dcelasun** [comment]
cc @allengeorge

**Comment by allengeorge** [comment]
Will take a look.

**Comment by allengeorge** [comment]
@sadroeck I'm sorry for taking so long to look at this.

First off, thank you for taking the time to look into the Rust code and second, for making the PR.

**Comment by allengeorge** [comment]
Merging, because the AppVeyor change looks unrelated.

**Comment by Jens-G** [comment]
> Merging, because the AppVeyor change looks unrelated.

You take care?

**Pull request closed without merging**
