### PR TITLE
supplement testcase for TProcesspoolServer(python)

### PR DESCRIPTION
**Pull request by zeshuai007**
- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by zeshuai007** [comment]
.

**Comment by Jens-G** [comment]
Travis does not look really great, could you check again?

**Comment by zeshuai007** [comment]
done

**Comment by zeshuai007** [comment]
> Travis does not look really great, could you check again?

done.

**Pull request closed without merging**
