### PR TITLE
THRIFT-4513: Fixing java thrift compiler to generate constants in stable order.

### PR DESCRIPTION
**Pull request by romanoid**
For description of the issue fixed, see: https://issues.apache.org/jira/browse/THRIFT-4513

### CODE REVIEW

**Comment by dcelasun** [comment]
Please add the issue number to your commit message and PR title. See [here](https://thrift.apache.org/docs/HowToContribute) (point 7 under Github).

**Comment by romanoid** [comment]
@jeking3 Yes, thanks, PR had some assumption on Map keys being only primitive for constant maps, which is not true in general. Latest revision should no longer rely on it.

**Comment by romanoid** [comment]
Updated approach:

t_const_value now defines ordering. 
Java generator changed to delegate to native ordering of t_const_value

**Comment by jeking3** [comment]
Please squash and rebase on master, I just merged 4 commits that stabilize the CI builds.

**Comment by romanoid** [comment]
@jeking3 done, thanks, let's see if it passes.

**Comment by romanoid** [comment]
Fix is in, the only failure left is this one, I'm not sure if it is instability of tests or real problem: https://travis-ci.org/apache/thrift/jobs/353050154

**Comment by jeking3** [comment]
Looks like a dlang issue that pops up from time to time.  Just to satisfy myself this change is okay I need to look at generated thrift file comparisons from before and after this change.  I'll do that locally.

**Comment by romanoid** [comment]
Thank you for the review!

**Pull request closed without merging**
