### PR TITLE
THRIFT-4313: Program code of the Erlang tutorial files contain syntax…

### PR DESCRIPTION
**Pull request by walter-weinmann**
… errors.

### CODE REVIEW

**Comment by walter-weinmann** [comment]
This closes #1342

**Comment by walter-weinmann** [comment]
This closes #1342

**Comment by walter-weinmann** [comment]
This closes #1342

**Comment by walter-weinmann** [comment]
This closes #1342.

**Comment by walter-weinmann** [comment]
This closes #1342.

**Comment by jeking3** [comment]
It looks like the autoconf build environment doesn't bother attempting to run the tutorial, so that's why it rotted.  Thanks for looking into this.  I am going to apply your changes locally and run the tutorial, and if it works I will merge it in.

**Comment by walter-weinmann** [comment]
This was only a minor issue - the bigger problem with the tutorial comes with THRIFT-4312.

**Comment by jeking3** [comment]
It would be nice to have some sort of check in the build that ensured it didn't rot again.  In the meantime, applying your patch allowed me to follow the tutorial readme, and without it I could not, so I am going to merge this.

**Pull request closed without merging**
