### PR TITLE
THRIFT-4509: update grunt to 1.0.2

### PR DESCRIPTION
**Pull request by bananer**
switch from grunt-external-daemon and grunt-shell to grunt-shell-spawn and update grunt to 1.0.2

### CODE REVIEW

**Comment by jeking3** [comment]
Any special considerations we need to add to the README for js or nodejs if we check in a package-lock.json file?  When distributing through npm should this file also be distributed?

**Comment by bananer** [comment]
The package-lock file keeps dependency versions fixed across all installations. According to [the docs](https://docs.npmjs.com/files/package-lock.json), this does not apply when the package is published on npm, where the file should be excluded.

To update the dependency packages for our builds, one now has to run `npm update` and commit the changed package-lock.json files. This does not impact users of thrift, so I'm not sure if it has to be noted in the Readme or somewhere else.

**Comment by jeking3** [comment]
Okay that sounds good; could you squash and rebase on master to prepare for a merge?

**Comment by bananer** [comment]
Rebased as https://github.com/apache/thrift/pull/1506

**Comment by jeking3** [comment]
In the future you can squash, rebase, and force push to keep the same PR, see:
https://thrift.apache.org/docs/HowToContribute

**Pull request closed without merging**
