### PR TITLE
Implement CONST support 

### PR DESCRIPTION
**Pull request by przygienda**

### CODE REVIEW

**Comment by Jens-G** [comment]
The description of this does not match the contents. We need to merge Rust first before we can patch it.

**Comment by Jens-G** [comment]
@maximg: Any comments from your side? Is this the merge request for Rust support just poorly named? Something is strange here.

**Comment by maximg** [comment]
Strange indeed, why would @przygienda try to push something from my repository. Please ignore this merge request for now.

**Comment by maximg** [comment]
@przygienda Rust for Thrift is developed in https://github.com/terminalcloud/thrift, if you want to get your changes upstream, could you open a merge request there? @Jens-G I believe this MR should be closed.

**Comment by Jens-G** [comment]
@jfarrell could you close this PR?

**Comment by Jens-G** [comment]
@jfarrell could you close this PR?

**Comment by anatol** [comment]
Rust is getting popular in service-side development world. Having Thrift-Rsut integration is mutually beneficial for both projects. So I would like to this this PR resolved.

Does anybody work on cleanup/upstreaming changes from above?

**Comment by Jens-G** [comment]
@anatol, please read the entire thread. 

The bottom line is that we (Thrift) patiently wait for @maximg to make the PR for Rust support. It's their code, therefore it is their decision whether or not they think that the Rust code is ready. This PR is from someone else not involved in the Thrift Rust stuff.

> Having Thrift-Rsut integration is mutually beneficial for both projects. So I would like to this this PR resolved.

I fully agree with you. If you want to speed up things by contributing, I could imagine that @maximg will be happy to get some feedback from third-party eyes. You should talk to him.

**Comment by anatol** [comment]
I googled the state of rust/thrift and found that the original repo from https://github.com/maximg/thrift has been abandoned, the development later moved to https://github.com/terminalcloud/thrift that also been abandoned and later picked up by https://github.com/jsgf/thrift/tree/rust that at this point contains the most complete set of rust changes.

There is also a ticked filed to track the Rust integration activity https://issues.apache.org/jira/browse/THRIFT-2945

**Comment by przygienda** [comment]
have a first rudimentary implementation of that on my branch. On top added something that allows to plug custom traits into the generated code (I used that to implement over redis-rs a trait to have REDIS persistency support). Looks like Thrift is moving pretty slowly and Rust for Thrift diverged into couple of branches ...

**Pull request closed without merging**
