### PR TITLE
ApacheThrift.nuspec: Updated to netstandard 2.1

### PR DESCRIPTION
**Pull request by emmenlau**
Currently the nuspec file is set to netstandard 2.0. As far as I know, the LTS version is netstandard 2.1. This PR increases the version to the LTS one.

- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  ([Request account here](https://selfserve.apache.org/jira-account.html), not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [x] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by Jens-G** [comment]
AFAIK it is still the case that if you want to target both NET framework and NET std the 2.0 is the version of choice. Am I wrong?

**Comment by emmenlau** [comment]
Ah, this may explain my problem. I want to share code with `.NET Core 3.x` and this did not work out of the box. Setting the netstandard to 2.1 helped. But I can see how this may break other use cases.

**Comment by Jens-G** [comment]
From [that same URL](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0#net-standard-not-deprecated):

> * Use netstandard2.0 to share code between .NET Framework and all other implementations of .NET.
> * Use netstandard2.1 to share code between Mono, Xamarin, and .NET Core 3.x.

**Comment by emmenlau** [comment]
Ok, maybe there is another problem on my side. I will retract this PR!

**Comment by Jens-G** [comment]
BTW, I would love to get rid of that as well. But that use case is not so uncommon I think. We actually use it at our company in exactly that combination where we have certain NET Standard modules included into existing older NET Framework 4.x applications that will most likely never be converted to NET Core for the rest of their life time.

**Pull request closed without merging**
