### PR TITLE
THRIFT-5523: [rs lib] use latest rust toolchain and edition 2021

### PR DESCRIPTION
**Pull request by Jimexist**
- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [x] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by Jimexist** [comment]
not sure if the build can be fixed by merging
- https://github.com/apache/thrift/pull/2522
first

**Comment by allengeorge** [comment]
@Jimexist Which version of Rust would you prefer we standardize on: 1.50 or 1.60? My take is 1.60, since that allows us to update to the 2021 edition as well?

**Comment by Jimexist** [comment]
this shall be rebased upon:
- #2628

**Comment by Jimexist** [comment]
see #2628

**Comment by allengeorge** [comment]
So, merge #2628 first and then update everything to 1.61?

**Pull request closed without merging**
