### PR TITLE
THRIFT-4007: TTransport.py micro-optimization: don't call len(chunk) twice

### PR DESCRIPTION
**Pull request by ndjensen**

### CODE REVIEW

**Comment by Jens-G** [comment]
Thanks! 
Could you also create a JIRA ticket according to our [contrib guidelines](http://thrift.apache.org/docs/HowToContribute)?

**Comment by Jens-G** [comment]
Ping @ndjensen

**Comment by Jens-G** [comment]
Ping @ndjensen

**Comment by ndjensen** [comment]
Sorry for the delay.  https://issues.apache.org/jira/browse/THRIFT-4007

**Comment by jeking3** [comment]
Hello - please rebase on master and force push.  I would like to see a CI build pass before merging; save perhaps job #17 which has been failing.

**Pull request closed without merging**
