### PR TITLE
THRIFT-3766: add zlib getUnderlyingTransport method

### PR DESCRIPTION
**Pull request by jeking3**
Client: C++

This closes #1370

### CODE REVIEW

**Comment by Jens-G** [comment]
Test

**Comment by jeking3** [comment]
@Jens-G test?

**Comment by Jens-G** [comment]
Yeah, test. I got only 2 mails this time. Your comment generated 3 mails. I had cases where I got up to 7 mails for one github comment.

**Comment by jeking3** [comment]
I've been really busy. :)

**Pull request closed without merging**
