### PR TITLE
THRIFT-4551: Run 'yarn prettier' to consistently format JS files

### PR DESCRIPTION
**Pull request by NameFILIP**
It's possible to add configuration using `prettier.config.js` to format the code in a specific way, but first see these:
[Prettier issue](https://github.com/prettier/prettier/issues/40)
[Dan Abramov talk (at 15:40)](https://youtu.be/G39lKaONAlA?t=939)

### CODE REVIEW

**Comment by jeking3** [comment]
@NameFILIP these changes broke the build.

**Comment by jeking3** [comment]
I rebased on master to get a clean build.

**Comment by jeking3** [comment]
Looks like there are still issues:
```
[jsl:jslint] /thrift/src/lib/js/src/thrift.js:322:5: Bad line breaking before '?'.
[jsl:jslint]     ? options.customHeaders
[jsl:jslint]     ^
[jsl:jslint] /thrift/src/lib/js/src/thrift.js:323:7: Bad line breaking before '?'.
[jsl:jslint]       ? options.customHeaders
[jsl:jslint]       ^
[jsl:jslint] /thrift/src/lib/js/src/thrift.js:384:9: Move the invocation into the parens that contain the function.
[jsl:jslint]       })();
[jsl:jslint]         ^
[jsl:jslint] /thrift/src/lib/js/src/thrift.js:392:9: Move the invocation into the parens that contain the function.
[jsl:jslint]       })();
[jsl:jslint]         ^
[jsl:jslint] /thrift/src/lib/js/src/thrift.js:603:11: Move the invocation into the parens that contain the function.
[jsl:jslint]         })()
[jsl:jslint]           ^
[jsl:jslint] /thrift/src/lib/js/src/thrift.js:628:13: Move the invocation into the parens that contain the function.
[jsl:jslint]           })()
[jsl:jslint]             ^
```

**Comment by NameFILIP** [comment]
yes, it conflicts with jslint rules.. which is not very flexible. Ideally, the project should be changed to use eslint which is much more powerful and is the industry standard and it should be good then.

**Comment by jeking3** [comment]
Cannot merge it as it breaks the build.  Will you be doing more work on this (eslint)?

**Comment by jeking3** [comment]
@NameFILIP will you be able to resolve these issues?

**Comment by jeking3** [comment]
@NameFILIP will you be able to resolve these issues?

**Comment by jeking3** [comment]
Going to try one more time... @NameFILIP will you be able to resolve these issues?

**Comment by jeking3** [comment]
I tried to do something similar with grunt-eslint, etc but this is not really an area I know well.  If the author wants to complete this work I would suggest eslint and using prettier in a lint mode for the grunt build.

**Pull request closed without merging**
