### PR TITLE
THRIFT-5341: Fix Old-Style-Cast, Missing override and Possible noexcept

### PR DESCRIPTION
**Pull request by kashirin-alex**
[THRIFT-5341](https://issues.apache.org/jira/browse/THRIFT-5341)

The changes were made over suggestions of GCC while compiling with the flags ` -Wsuggest-override` and `-Wold-style-cast`.

The Old-Style-Cast summed down to enumerations and a double, whereas `override` was added to all the functions that are inherited/extended the associated base.

plus, variables in a class Constructor changed into each in it's own line, as such:
```cpp
class Schema : public virtual ::apache::thrift::TBase {
 public:

  Schema(const Schema&);
  Schema& operator=(const Schema&);
  Schema() : cid(0),
             col_name(),
             col_seq(static_cast<KeySeq::type>(0)),
             col_type(static_cast<ColumnType::type>(0)),
             cell_versions(0),
             cell_ttl(0),
             blk_encoding(static_cast<EncodingType::type>(0)),
             blk_size(0),
             blk_cells(0),
             cs_replication(0),
             cs_size(0),
             cs_max(0),
             log_rollout_ratio(0),
             log_compact_cointervaling(0),
             log_fragment_preload(0),
             compact_percent(0),
             revision(0) {
  }
```
The same `class Schema` by Thrift-0.13.0 was https://github.com/kashirin-alex/swc-db/blob/414326d40f72c9e4f054e475dbd31fffe932df4d/src/thrift/swcdb/thriftgen-0.13.0/gen-cpp/Service_types.h#L352

### CODE REVIEW

**Comment by kashirin-alex** [comment]
with the checks being cancelled/errored (null-rsp. on travis) 
At this point I know of one build test with success https://ci.appveyor.com/project/ApacheSoftwareFoundation/thrift/builds/37486127

How should the checks to be proceed/queued ? (I don't have any additional commits/changes for this pull-request - to queue a new build check)

**Comment by Jens-G** [comment]
If a CI fails sometimes it helps to force push to trigger a new CI run. 
With regard to reviewing this I would recommend to the C++ people.around.

**Comment by emmenlau** [comment]
Dear @kashirin-alex , the changes you did look valuable, thanks for this contribution! I would like to review them more thoroughly but its not a trivial change and I would need significantly more time for a good review. If somebody else can jump in thats great, otherwise I may find some time in the next months (but not in the short term, sorry).

**Comment by kashirin-alex** [comment]
@emmenlau , Yes it does stand as relaxed-changes, eg. `-Wno-error=*` https://github.com/kashirin-alex/swc-db/blob/3c910bee2f9c5eaa4a737638827fdc0400debd1c/CMakeLists.txt#L74
Thanks

**Comment by kashirin-alex** [comment]
True cause of the error (type-ptr-N was equal to already checked fields-members type-ptr-N )
 * https://travis-ci.org/github/apache/thrift/jobs/757915515#L13765
 
 lib/cpp/# `make test`:
```
100% tests passed, 0 tests failed out of 25
Total Test time (real) = 191.02 sec
```

**Comment by Jens-G** [comment]
Is this ready for merge or still in progress?

**Comment by kashirin-alex** [comment]
You can have additional insight on the changes there are with this commit:
 https://github.com/kashirin-alex/swc-db/commit/8b200d1ce763f865b403999cd51fb8c7cf3913be

**Comment by Jens-G** [comment]
@emmenlau could you have a look at this & possibly merge if all is fine?

**Pull request closed without merging**
