### PR TITLE
THRIFT-4536: Rust 1.34.0

### PR DESCRIPTION
**Pull request by dbcfd**
Update dockerfiles to use rust stable, call out required rust version in
breaking changes.

  

- [X] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [X] Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?  (not required for trivial changes)
- [X] Did you squash your changes to a single commit?
- [X] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"

### CODE REVIEW

**Comment by dbcfd** [comment]
@allengeorge Do you know of any other build scripts that need rust stable?

**Comment by Jens-G** [comment]
@dbcfd could you force-push this again please?

**Comment by dbcfd** [comment]
@Jens-G simple force didn't work, deleted/pushed and reopened.

Appveyor failed with 
`
> jdk8 v8.0.201 [Approved]
jdk8 package files install completed. Performing other installation steps.
Downloading JDK from http://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-windows-x64.exe
ERROR: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
The install of jdk8 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\jdk8\tools\chocolateyInstall.ps1'.
 See log for details.
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
 - jdk8 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\jdk8\tools\chocolateyInstall.ps1'.
 See log for details.`

**Comment by Jens-G** [comment]
merged, thanks

**Pull request merged**
