### PR TITLE
Added async nonblocking ssl support in java client

### PR DESCRIPTION
**Pull request by dthaluru**

### CODE REVIEW

**Comment by jeking3** [comment]
Is there a Jira ticket for this improvement?  See: https://thrift.apache.org/docs/HowToContribute
In addition, are the existing unit tests sufficient to cover the changes?

**Comment by jeking3** [comment]
@Jens-G does the current cross suite exercise asynchronous sufficiently to test these changes?

**Comment by jeking3** [comment]
@dthaluru Is there a Jira ticket for this improvement? See: https://thrift.apache.org/docs/HowToContribute
In addition, are the existing unit tests sufficient to cover the changes?

@Jens-G does the current cross suite exercise asynchronous sufficiently to test these changes?

**Comment by dthaluru** [comment]
Sorry for late response. @jeking3 There is no Jira ticket for this feature.
Current unit tests does not cover this feature.  Current implementation of non-blocking async java client does not seems to work with blocking java server.  To add unit test for this feature, the above mentioned issue need to be fixed. I have talked with @RandyAbernethy offline. I will sent more details in mail.

**Comment by jeking3** [comment]
It would be nice to see it tested in make cross somehow.

**Comment by jeking3** [comment]
@dthaluru, @RandyAbernethy any updates?

**Comment by RandyAbernethy** [comment]
I can get to this this weekend.

**Comment by jeking3** [comment]
We should add async servers to the cross test suite.

**Comment by jeking3** [comment]
Any thoughts on moving this one forward?

**Comment by jeking3** [comment]
Someone needs to open a Jira ticket for this too, and it would be nice to have a cross test to verify it against all ssl servers.

**Comment by jeking3** [comment]
Still needs a Jira ticket...

**Comment by jeking3** [comment]
Needs a Jira ticket.
Needs cross tests.

**Comment by jeking3** [comment]
As I have been the only contributor to the conversation on this pull request for the last year, I'm closing this.  Feel free to re-open if you have updates.

**Pull request closed without merging**
