### PR TITLE
THRIFT-5762 Fix spotless errors

### PR DESCRIPTION
**Pull request by thomasbruggink**
Run `gradlew :spotlessApply` to apply the correct coding style.

### CODE REVIEW

**Comment by thomasbruggink** [comment]
@fishy is there anything i can run locally to test if the cross test will start?

**Comment by fishy** [comment]
A later step for kotlin failed: https://github.com/apache/thrift/actions/runs/8294540230/job/22710000124?pr=2945

>is there anything i can run locally to test if the cross test will start?

Not really, but you can look at the github action workflow definition and run the steps manually locally: https://github.com/apache/thrift/blob/0e7236391f9ac7482f2e62a8c30155e015a80aa9/.github/workflows/build.yml#L192

**Comment by thomasbruggink** [comment]
@fishy I fixed the kotlin compiler error, didnt realize this was re-using the java library :bow: 
If you prefer this to be its own PR let me know and I'll split it off.

**Review by fishy — APPROVED** [review]
looks good to me, but I'll give others more familiar with the java/kotlin code a chance to review before merging it.

in the mean time, @thomasbruggink can you please squash the commits?

**Pull request merged**
