### PR TITLE
THRIFT-1313 implement compact protocol for c_glib library

### PR DESCRIPTION
**Pull request by cjmay**
Implement compact protocol for c_glib library, add tests.

### CODE REVIEW

**Comment by bufferoverflow** [comment]
Great work!
Could you please add this to ``test/tests.json`` as well

**Comment by jeking3** [comment]
Along with adding it to tests.json, ensure `make cross` passes.

**Comment by cjmay** [comment]
Thanks for the feedback!  I added the c_glib compact protocol to test/tests.json and cross tests now pass.

**Comment by jeking3** [comment]
Your commitment to testing is admirable!  Looks good to me for merge.

**Pull request closed without merging**
