### PR TITLE
THRIFT-3728 http transport for thrift-lua

### PR DESCRIPTION
**Pull request by mygityf**
THttpTransport.lua is http transport implement for thrift-lua.

### CODE REVIEW

**Comment by mygityf** [comment]
Jenkins and CI error：
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x0000000291dc58>
/var/lib/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/rake_task.rb:124:in `initialize'

**Comment by nsuke** [comment]
Can you rebase your branch ?
The problem is fixed in 3fe8b0fe855ec9b7adfa3ac90e6c5dae53d79738

**Comment by mygityf** [comment]
CI looks failure in cases of d-lua http-ip with all protocol.
it is bug in thrift-d library at file http.d.
#942

**Comment by mygityf** [comment]
CI Error:
precision lost from double to string.
https://github.com/apache/thrift/pull/948
https://github.com/gityf/thrift/commit/5a2b9cd39f6088dc5ccc726e7c0d483c5d7470ee

**Comment by mygityf** [comment]
@nsuke All checks done.

**Pull request closed without merging**
