### PR TITLE
uncaught_exception -> uncaught_exceptions

### PR DESCRIPTION
**Pull request by rolesen**
- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [ ] Did you squash your changes to a single commit?  (not required, but preferred)
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by rolesen** [comment]
Let me know if anything missing before it can be integrated (?)

**Comment by Jens-G** [comment]
Not sure but ...

```
/thrift/src/compiler/cpp/thrift --gen cpp ../../../test/Recursive.thrift
/thrift/src/compiler/cpp/thrift --gen cpp ../../../test/ThriftTest.thrift
/thrift/src/compiler/cpp/thrift --gen cpp ../../../test/TypedefTest.thrift
/thrift/src/compiler/cpp/thrift --gen cpp:templates,cob_style processor/proc.thrift
[WARNING:/thrift/src/test/ThriftTest.thrift:43] No generator named 'noexist' could be found!
[WARNING:/thrift/src/test/ThriftTest.thrift:45] cpp generator does not accept 'noexist' as sub-namespace!
/thrift/src/compiler/cpp/thrift --gen cpp:templates,cob_style processor/proc.thrift
/thrift/src/compiler/cpp/thrift --gen cpp OneWayTest.thrift
/thrift/src/compiler/cpp/thrift --gen cpp OneWayTest.thrift
terminate called after throwing an instance of 'std::__ios_failure'
  what():  basic_ios::clear: iostream error
Makefile:1741: recipe for target 'gen-cpp/OneWayService.h' failed
make[3]: *** [gen-cpp/OneWayService.h] Aborted (core dumped)
make[3]: *** Deleting file 'gen-cpp/OneWayService.h'
make[3]: Leaving directory '/thrift/src/lib/cpp/test'
Makefile:1531: recipe for target 'check-recursive' failed
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory '/thrift/src/lib/cpp'
Makefile:579: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/thrift/src/lib'
Makefile:679: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

**Comment by rolesen** [comment]
Why should that throw only in that particular test. My initial guess is this is something unrelated to this PR, although I haven't run any cross tests.

**Comment by Jens-G** [comment]
Thanks for the patch! 

I took the liberty to only merge the relevant part of this patch, but left out the other unrelated changes.
Feel free to send a separate patch that covers the missing overrides, in all affected files.

**Pull request closed without merging**
