### PR TITLE
THRIFT-5378: Amend Go String() generation for enums

### PR DESCRIPTION
**Pull request by maguro**

### CODE REVIEW

**Comment by Jens-G** [comment]
Could you force push again? CI seems not related but its largely red, so let us just try again.

**Comment by maguro** [comment]
> Could you force push again? CI seems not related but its largely red, so let us just try again.

Still have errors that don't seem to have anything to do w/ the PR.  Is there a ticket to fix the CI checks?  I can try to help.

**Comment by fishy** [comment]
Copying the comment I left on the JIRA ticket here:

>The PR you made generated essentially the same go code, so you must have some other issue caused the problem. Can you provide a minimal example with detailed steps (for example, which version of which debugger are you using and on which platform) to reproduce the issue?

**Comment by maguro** [comment]
Unable to reproduce original problem.

**Pull request closed without merging**
