### PR TITLE
THRIFT-5133: Use ArrayPool when reading and writing strings to improve performance. 

### PR DESCRIPTION
**Pull request by CodeBlanch**
Uses ArrayPool to save on buffer allocations when reading/writing strings.

Related to #2043.

### CODE REVIEW

**Comment by CodeBlanch** [comment]
I made a couple changes that might be unpopular but worth doing IMO:

1) Added benchmark project. This was to isolate the changes in order to more accurately measure the performance. Can be built upon in the future to measure other things.
2) Multi-target .NET Standard 2.1 on the Thrift library to access the ReadAsync ValueTask Stream API additions. Greatly reduces allocations performing reads.

### .NET 4.8 Benchmarks
``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
Intel Core i9-9880H CPU 2.30GHz, 1 CPU, 16 logical and 8 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4150.0), X64 RyuJIT
  DefaultJob : .NET Framework 4.8 (4.8.4150.0), X64 RyuJIT


```
|      Method | NumberOfOperationsPerIteration |     Mean |     Error |    StdDev |    Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------ |------------------------------- |---------:|----------:|----------:|---------:|------:|------:|----------:|
| WriteString |                          10000 | 2.920 ms | 0.0581 ms | 0.0714 ms |  74.2188 |     - |     - | 470.15 KB |
|  ReadString |                          10000 | 5.939 ms | 0.1166 ms | 0.1780 ms | 367.1875 |     - |     - | 2272.4 KB |

After:
``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
Intel Core i9-9880H CPU 2.30GHz, 1 CPU, 16 logical and 8 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4150.0), X64 RyuJIT
  DefaultJob : .NET Framework 4.8 (4.8.4150.0), X64 RyuJIT


```
|      Method | NumberOfOperationsPerIteration |     Mean |     Error |    StdDev |    Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------ |------------------------------- |---------:|----------:|----------:|---------:|------:|------:|----------:|
| WriteString |                          10000 | 3.322 ms | 0.0628 ms | 0.0645 ms |        - |     - |     - |         - |
|  ReadString |                          10000 | 5.863 ms | 0.0941 ms | 0.0834 ms | 367.1875 |     - |     - | 2326867 B |

### .NET Core 3.1 Benchmarks
Before:
``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
Intel Core i9-9880H CPU 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=3.1.101
  [Host]     : .NET Core 3.1.2 (CoreCLR 4.700.20.6602, CoreFX 4.700.20.6702), X64 RyuJIT
  DefaultJob : .NET Core 3.1.2 (CoreCLR 4.700.20.6602, CoreFX 4.700.20.6702), X64 RyuJIT


```
|      Method | NumberOfOperationsPerIteration |     Mean |     Error |    StdDev |    Gen 0 | Gen 1 | Gen 2 |  Allocated |
|------------ |------------------------------- |---------:|----------:|----------:|---------:|------:|------:|-----------:|
| WriteString |                          10000 | 1.359 ms | 0.0222 ms | 0.0197 ms |  56.6406 |     - |     - |  468.75 KB |
|  ReadString |                          10000 | 3.322 ms | 0.0376 ms | 0.0352 ms | 257.8125 |     - |     - | 2109.42 KB |

After:
``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
Intel Core i9-9880H CPU 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=3.1.101
  [Host]     : .NET Core 3.1.2 (CoreCLR 4.700.20.6602, CoreFX 4.700.20.6702), X64 RyuJIT
  DefaultJob : .NET Core 3.1.2 (CoreCLR 4.700.20.6602, CoreFX 4.700.20.6702), X64 RyuJIT


```
|      Method | NumberOfOperationsPerIteration |     Mean |     Error |    StdDev |   Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------ |------------------------------- |---------:|----------:|----------:|--------:|------:|------:|----------:|
| WriteString |                          10000 | 1.614 ms | 0.0315 ms | 0.0420 ms |       - |     - |     - |         - |
|  ReadString |                          10000 | 3.812 ms | 0.0092 ms | 0.0082 ms | 85.9375 |     - |     - |  720000 B |

**Comment by Jens-G** [comment]
https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/

> Given many of the API additions in .NET Standard 2.1 require runtime changes in order to be meaningful, .NET Framework 4.8 will remain on .NET Standard 2.0 rather than implement .NET Standard 2.1.

IIRC this will break then compatibility with NET Framework. That's why we reset it to 2.0.

https://issues.apache.org/jira/browse/THRIFT-4990

**Comment by CodeBlanch** [comment]
> IIRC this will break then compatibility with NET Framework. That's why we reset it to 2.0.

Your recall is 100% spot-on, that's why I didn't _change_ the target, I _added_ one. Subtle, but important difference. The library is now targetting .NET Standard 2.0 & .NET Standard 2.1 at the same time. When you compile you get 2 DLLs, one for each. Both can be included in the NuGet and then consumers can use whichever they support.

You can see this right now in practice in the Benchmark project. It is a Console app (EXE) multi-targeting .NET Framework 4.8 and .NET Core 3.1. When compiled, two exes. One will use the .NET Standard 2.0 path and the other .NET Standard 2.1.

The idea being, we support people on older versions but if you are using .NET Core 3+, we can take advantage of the performance improvements available.

**Comment by Jens-G** [comment]
Great!

**Pull request closed without merging**
