### PR TITLE
THRIFT-4039: Update of Apache Thrift .Net Core lib

### PR DESCRIPTION
**Pull request by vgotra**
Changes to library:
- Updated tutorial (added samples of usage of multiplexed protocol to server and client side and other)
- Added framed transport to client side and implementation of framed transport to server 
- Updated information related to build of thrift application with CMake, Visual Studio 2017, XCode
- Updated information related to build and usage of Thrift .Net Core library 
- Added SDK versions to project for easy usage of different versions of .NET Core SDK

### CODE REVIEW

**Comment by Jens-G** [comment]
http://thrift.apache.org/docs/HowToContribute

**Comment by vgotra** [comment]
Hi @Jens-G 

Added pull request with changes described in Jira task and in pull request. 

Later after stabilizing and release of .NET Standard 2.0 I will create new request with migration to latest stable .NET Core SDK. 

Thanks

**Comment by vgotra** [comment]
Hi @Jens-G  

It seems that we have first less-more stable version of .Net Core SDK/CLI and .NET Core runtime. Also it is possible to create and run unit and integration tests with .Net Core now. 

So, I want to start work on unit tests (maybe also on integration tests) and upgrade library to current stable version of  .Net Core.

The only question for me - how do you build libraries on build server and also how I can find some basic help about how to do that. It will be good to know to avoid issues with changes. 

Also it will be great to understand how do you include some new frameworks into Thrift.exe generator to easy include generation of .Net Core generator into official Thrift.exe generator - some people asked me recently how to build it because .Net Core generator still not included into Thrift.exe. 

P.S. As always I will create task in Apache Jira for new pull request )

Thanks 
Volodymyr

**Comment by Jens-G** [comment]
> because .Net Core generator still not included into Thrift.exe.

It's included in trunk, not in 0.10. The release was already at the door so I didn't want to pollute it with a newly included target that may need some time to be thorougly tested and stable. It will be in the next release. When you build the compiler from trunk, you get it right now.

> The only question for me - how do you build libraries on build server and also how I can find some basic help about how to do that. It will be good to know to avoid issues with changes.

Automake scripts do still work, and to my knowledge it is also included in the CMake scripts.

**Pull request closed without merging**
