### PR TITLE
THRIFT-5288: Move Support for ByteBuffer into TTransport

### PR DESCRIPTION
**Pull request by belugabehr**
- [X] Did you create an [THRIFT-5288](https://issues.apache.org/jira/browse/THRIFT-5288)
- [X] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [X] Did you squash your changes to a single commit?  (not required, but preferred)
- [X] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [X] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by Jens-G** [comment]
make[3]: Entering directory '/thrift/src/lib/java'
./gradlew  assemble \
	-Prelease=true \
	-Pthrift.version=0.14.0 \
	--console=plain
> Task :copyDependencies

> Task :compileJava
/thrift/src/lib/java/src/org/apache/thrift/transport/THttpClient.java:39: warning: [deprecation] CoreConnectionPNames in org.apache.http.params has been deprecated
import org.apache.http.params.CoreConnectionPNames;
                             ^
/thrift/src/lib/java/src/org/apache/thrift/transport/TNonblockingTransport.java:52: error: write(ByteBuffer) in TNonblockingTransport cannot override write(ByteBuffer) in TTransport
  public abstract int write(ByteBuffer buffer) throws IOException;
                      ^
  return type int is not compatible with void
/thrift/src/lib/java/src/org/apache/thrift/transport/TNonblockingSocket.java:170: error: write(ByteBuffer) in TNonblockingSocket cannot override write(ByteBuffer) in TTransport
  public int write(ByteBuffer buffer) throws IOException {
             ^
  return type int is not compatible with void
/thrift/src/lib/java/src/org/apache/thrift/meta_data/FieldMetaData.java:61: warning: [deprecation] newInstance() in Class has been deprecated
        sClass.newInstance();
              ^
  where T is a type-variable:
    T extends Object declared in class Class
/thrift/src/lib/java/src/org/apache/thrift/transport/THttpClient.java:165: warning: [deprecation] CoreConnectionPNames in org.apache.http.params has been deprecated
      client.getParams().setParameter(CoreConnectionPNames.CONNECTION_TIMEOUT, connectTimeout_);
                                      ^
/thrift/src/lib/java/src/org/apache/thrift/transport/THttpClient.java:165: warning: [deprecation] getParams() in HttpClient has been deprecated
      client.getParams().setParameter(CoreConnectionPNames.CONNECTION_TIMEOUT, connectTimeout_);
            ^
/thrift/src/lib/java/src/org/apache/thrift/transport/THttpClient.java:174: warning: [deprecation] CoreConnectionPNames in org.apache.http.params has been deprecated
      client.getParams().setParameter(CoreConnectionPNames.SO_TIMEOUT, readTimeout_);
                                      ^
/thrift/src/lib/java/src/org/apache/thrift/transport/THttpClient.java:174: warning: [deprecation] getParams() in HttpClient has been deprecated
      client.getParams().setParameter(CoreConnectionPNames.SO_TIMEOUT, readTimeout_);
            ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
6 warnings

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
2 actionable tasks: 2 executed

**Comment by belugabehr** [comment]
Woops.  I thought I was adding functionality, but I guess I was actually overwriting.  I just made a new push, we'll see what happens, but I am definitely breaking API here by changing method signatures.

**Comment by belugabehr** [comment]
@Jens-G Hey, can you help me figure out what is causing this build failure?  It seems to be to be related to Erlang, but I'm not 100% sure.

**Comment by Jens-G** [comment]
Right, not your problem. Some Erlang problems that (still) need to be fixed.

**Pull request closed without merging**
