### PR TITLE
ci(rust): Add release workflow for rust

### PR DESCRIPTION
**Pull request by Xuanwo**
This PR adds release workflow for rust which will do `cargo publish` while tagged.

- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  ([Request account here](https://selfserve.apache.org/jira-account.html), not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by Xuanwo** [comment]
cc @Jens-G, Would you like to take a look, thanks!

To make this workflow work, we also need to set a new secret call `CARGO_REGISTRY_TOKEN`.

**Comment by Jens-G** [comment]
LGTM but I have not really too much expertise with Rust, so a second pair of eyes is more than appreciated.

**Comment by Xuanwo** [comment]
> LGTM but I have not really too much expertise with Rust, so a second pair of eyes is more than appreciated.

Hi, @Jens-G, it seems no one else has reviewed this yet. However, this workflow has been successfully used in many other projects. For example:

- OpenDAL: https://github.com/apache/opendal/blob/main/.github/workflows/release_rust.yml
- Iceberg-Rust: https://github.com/apache/iceberg-rust/blob/main/.github/workflows/publish.yml#L46

Would this be valuable for your review?

**Comment by jimexist** [comment]
this `CARGO_REGISTRY_TOKEN` needs to be added to GitHub repo itself right? i as a committer would not be able to do that, it requires some admin role in the repo itself.

**Comment by Xuanwo** [comment]
> this `CARGO_REGISTRY_TOKEN` needs to be added to GitHub repo itself right? i as a committer would not be able to do that, it requires some admin role in the repo itself.

Yes. We will need one of our PMC members to contact with the INFRA team to get it setup.

**Comment by Xuanwo** [comment]
We can take those tickets as examples: 

- https://issues.apache.org/jira/projects/INFRA/issues/INFRA-25132
- https://issues.apache.org/jira/browse/INFRA-25951

**Comment by Jens-G** [comment]
https://issues.apache.org/jira/browse/INFRA-26083

**Comment by Xuanwo** [comment]
> [issues.apache.org/jira/browse/INFRA-26083](https://issues.apache.org/jira/browse/INFRA-26083)

Thank you, @Jens-G, for this!

**Comment by Jens-G** [comment]
INFRA has added the token.

**Comment by Xuanwo** [comment]
> INFRA has added the token.

Thanks!

**Pull request closed without merging**
