### PR TITLE
THRIFT-4764: Use new syntax for clippy skipping

### PR DESCRIPTION
**Pull request by MikailBag**
Client: rs

### Pull Request ###

The [Contributing Guide](https://github.com/apache/thrift/blob/master/CONTRIBUTING.md) has more details and tips for
committing properly.

Review the following checklist to ensure a smooth pull request experience.

- [x] Did you squash your changes to a single commit?

- [ ] Do you need an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?<details><summary>Expand for guidance...</summary>
    - `Yes` if your change requires a release note.
    - `Yes` if your change is a breaking change.
    - `No` if you change is trivial, such as fixing a typo.
</details>
 
- [ ] Is this change worthy of a release note? <details><summary>Examples of Release Note-worthy examples...</summary>
    - Breaking Changes
    - New, Deprecated, or Removed Languages
    - Security Fixes
    - Significant Refactoring
    - Changing how the product is built
</details>

- [ ] Breaking changes have additional requirements: <details><summary>Expand for instructions...</summary>
    - Add or reference an existing Apache Jira THRIFT ticket.
    - Add a `Breaking-Change` label to the Jira ticket.
    - Add a note to the `lib/<language>/README.md` file.
    - Add a line to the `CHANGES.md` file.
</details>

- [x] Does this change require a build? <details><summary>Expand for guidance...</summary>
    - `Yes` for any code change
    - `Yes` for any build script change
    - `Yes` for any docker build environment change
    - `Yes` for any change affecting the cross test suite
    - `No` for documentation-only changes
    - `No` for trivial changes, for example fixing a typo.
    <br/>
    If your change does not require a build, you can add [ci skip] to the end of your commit message.<br/>
    This will avoid costly and unnecessary builds in both the pull request and once it is merged.
</details>

For more information about committing, see the [Contributing Guide](https://github.com/apache/thrift/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mrwiggles** [comment]
Sorry @jeking3 - been super busy after work for the past month :/

**Comment by mrwiggles** [comment]
Looking now

**Comment by mrwiggles** [comment]
@MikailBag All of the rust builds are failing, unfortunately. I suspect this is because the Rust version has to be bumped as well for the new clippy attributes to be understood.

**Comment by MikailBag** [comment]
Oh, it seems that new syntax was only introduced in rustc v1.31, which was published 2018-12-06.

**Comment by jeking3** [comment]
If you can make it backwards compatible, great, otherwise we can't accept something that would push the minimum required version forward that far.

**Comment by MikailBag** [comment]
Ok. Than I think I should close this PR, because I can't make changes backwards-compatible, and suppressing the lint is easy.

**Comment by allengeorge** [comment]
Since the Rust-version has been updated to 1.36, I believe we should be able to reapply this.

**Pull request closed without merging**
