### PR TITLE
THRIFT-5776: Cpp cross test fail test

### PR DESCRIPTION
**Pull request by CJCombrink**
[THRIFT-5776](https://issues.apache.org/jira/browse/THRIFT-5776)

- Not yet sure where the issue might be

  

- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  ([Request account here](https://selfserve.apache.org/jira-account.html), not required for trivial changes)
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [ ] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by Jens-G** [comment]
Still draft?

**Comment by CJCombrink** [comment]
@Jens-G I still need to look into the latest errors as mentioned on the ticket. 
However when I was testing this was sufficient to to get the `build/docker/scripts/autotools.sh` script to pass, but the OP seems to have more issues.

**Comment by CJCombrink** [comment]
@Jens-G Sorry for the delay, I am looking into this this week, I could not over the weekend.

**Comment by CJCombrink** [comment]
@Jens-G The last commits at least fixes the compile errors in the 'ubuntu-jammy' docker containers as well.
I have not implemented any cross tests, just made it compile. 
I can look at better cross tests but would like to get some feedback on [THRIFT-5773](https://issues.apache.org/jira/browse/THRIFT-5773) so that I can do the work there.

After these changes I now also get [THRIFT-5775](https://issues.apache.org/jira/browse/THRIFT-5775) as per the original ticket tracking this issue.

**Comment by CJCombrink** [comment]
Fixed as part of #2958

**Pull request closed without merging**
