### PR TITLE
THRIFT-5587 Introduce uuid as additional builtin type (partially implemented)

### PR DESCRIPTION
**Pull request by Jens-G**
Contains:
* Replace ThriftTest.thrift with ThriftTest_0_16.thrift to allow for merging the partially completed uuid implementation to master
* THRIFT-5587 add uuid support for java and kotlin
* THRIFT-5593 Implement uuid for Haxe
* Add uuid type to XSD
* THRIFT-5591 Add uuid type to IDL and implement reference code

Attempt to get the uuid branch cleaned up and mergeable. The ThriftTest.thrift IDL file has been duplicated to have a full version (The ThriftTest.thrift) and a 0.16.x version without uuids (ThriftTest_0_16.thrift) for those language bindings where uuid is not yet available/implemented. When some language implements it, the test file should again be ThriftTest.thrift so that at some point in the future the 0.16.x IDL file can be safely removed.

### CODE REVIEW

**Review by Jimexist — APPROVED** [review]

**Comment by Jimexist** [comment]
maybe:
- https://github.com/apache/thrift/pull/2627/files
can fix the issue

**Comment by Jens-G** [comment]
@Jimexist Could you have a look at that and the gradle issue as well?

> TestStandardScheme > testPersistentStructs() FAILED
>    org.opentest4j.AssertionFailedError at TestStandardScheme.java:44

**Comment by Jimexist** [comment]
> @Jimexist Could you have a look at that and the gradle issue as well?
> 
> > TestStandardScheme > testPersistentStructs() FAILED
> > org.opentest4j.AssertionFailedError at TestStandardScheme.java:44

i'm not sure i can find that error - can you point me the link? i want to know which branch and build

**Comment by Jimexist** [comment]
also i think "Build / lib-java-kotlin (pull_request)" shall be able to catch all Java related errors and it is green in this pull request

**Comment by Jens-G** [comment]
https://app.travis-ci.com/github/apache/thrift/jobs/575401321

**Pull request closed without merging**
