### PR TITLE
Update thrift_socket_transport.erl

### PR DESCRIPTION
**Pull request by TianMaiChengGhostRidder**
如果传送的数据量大的时候就会报错。

  

- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [ ] Did you squash your changes to a single commit?  (not required, but preferred)
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by TianMaiChengGhostRidder** [comment]
如果传送的数据量很小，不会出错。如果传送的数量大的时候就会出错。
图片
图片
代码修改后，传送大量数据就不会出错了。

**Comment by Jens-G** [comment]
Can we have that in english please? Thank you!

**Comment by TianMaiChengGhostRidder** [comment]
If we transmit a large amount of data, we will make an error. It should be modified to the following code:
图片

**Comment by Jens-G** [comment]
May I ask what error you get specifically?

**Comment by TianMaiChengGhostRidder** [comment]
The error is marked in the above picture. Please note that it is not my error, but the Erlang library error. You can modify it according to my screenshot. This is machine translated English. It is estimated that the semantics are a bit wrong

**Comment by TianMaiChengGhostRidder** [comment]
I have pointed out the mistake
Why is the master branch of Erlang library not updated

**Comment by Jens-G** [comment]
> Why is the master branch of Erlang library not updated

Because nobody did it?

**Pull request merged**
