### PR TITLE
THRIFT-3775: 0.10.0 release

### PR DESCRIPTION
**Pull request by jfarrell**
Initial versioning switch for the 0.10.0 release candidate 

Please do not merge this to master, I will commit this patch when it is passing all tests to the release branch and start the vote thread

### CODE REVIEW

**Comment by jfarrell** [comment]
@RandyAbernethy @Jens-G @jeking3 any of you aware of the appveyor openssl issue this build just triggered?

```
appveyor DownloadFile https://slproweb.com/download/Win64OpenSSL-%OPENSSL_VERSION%.exe
Error downloading remote file: One or more errors occurred.
```

**Comment by jeking3** [comment]
@Jens-G I saw some updates from @nsuke on this overnight.  It would be in https://issues.apache.org/jira/browse/THRIFT-3934.

**Comment by jeking3** [comment]
I also want to get THRIFT-3936 in, it's a simple change to PlatformSocket.h and TServerSocket.h that was introduced during 0.10.0 development which makes it fail to compile on VS2013 and earlier.

**Comment by jeking3** [comment]
I fixed the appveyor issue as part of THRIFT-3936.

**Comment by jeking3** [comment]
@jfarrell should this be closed now?

**Comment by jfarrell** [comment]
had left it open while still publishing the packages, can close it out and continue that in the background now that the source release is out

**Comment by tylertreat-wf** [comment]
@jfarrell Was 0.10.0 released? I don't see it listed under the releases.

**Comment by jfarrell** [comment]
@tylertreat-wf just pushed the [0.10.0 tag](https://git-wip-us.apache.org/repos/asf?p=thrift.git;a=tag;h=ae93ff0b4bdbd6749f75c23ad23311b512230894), once the mirror picks it up github will have it

**Comment by renstrom** [comment]
What about language bindings? More specifically, the Python package on [PyPi](https://pypi.python.org/pypi/thrift).

**Comment by bgould** [comment]
Also it appears the Java library and thrift-maven-plugin haven't made it into Maven central yet:

https://repo.maven.apache.org/maven2/org/apache/thrift/

**Pull request closed without merging**
