### PR TITLE
THRIFT-4809: Implement episodic compilation for js code generation

### PR DESCRIPTION
**Pull request by mustafa-cosar**
Implement episodic compilation for js code generation

Two new options are:
`thrift_package_output_directory`: If set, the generator will create an episode file `thrift.js.episode` that will contain the import paths of the generated modules. `thrift_package_output_directory` will be a prefix for the import path. This episode file then should be placed in the root of the node_module.

`imports`: The `:` separated paths of node_modules to import from. The node_module must have `thrift.js.episode` file in the module root. This option is mutually exclusive with `-recurse` option.

### CODE REVIEW

**Comment by mustafa-cosar** [comment]
Hi @jeking3,
Can you review this PR?
I noticed that there are failures in travis but they are not related to me. My test was run and it passed.

**Comment by jeking3** [comment]
Rebase on master as I fixed the xenial issue.

**Comment by mustafa-cosar** [comment]
Hi @jeking3, there seems to be other failures

**Comment by jeking3** [comment]
Something changed in haskell land, or hackage is down (again).  I'll look at it when I can..

**Comment by mustafa-cosar** [comment]
Ping @jeking3

**Comment by jeking3** [comment]
Yeah, haskell is still busted, even on other PRs.  I haven't had time to look yet.

**Comment by thehcma** [comment]
hi @jeking3 - any hope this PR will be merged?

**Comment by jeking3** [comment]
Haskell is still busted and I'm not qualified to review more complex JavaScript PRs... I don't know the language other than casual use.

**Comment by thehcma** [comment]
@jeking3 - can you please suggest someone to help get this reviewed (btw, I work with @mustafa-cosar and we (myself and @bgedik) have (internally) reviewed and tested this.

**Comment by mustafa-cosar** [comment]
Hi @jeking3 
I rebased on master

**Comment by mustafa-cosar** [comment]
@jeking3 ping

**Comment by mustafa-cosar** [comment]
> I kicked the failing job which had some java-cpp cross test timeouts.

The travis build is green, but appveyor failed at the start. Will you kick another build or is travis enough?

Thanks

**Pull request merged**
