### PR TITLE
THRIFT-5285 Update http package + update to dart 2 + stylistic changes

### PR DESCRIPTION
**Pull request by aaronstgeorge-wf**
This PR only touches dart sections

http 0.11.x will not build on dart 2. This PR widens the range to include 0.12.x.

Additional non essential changes:

- Dart 1 is now deprecated, this pull request updates thrift dart library to be solely dart 2 compatible.
- Adds some stylistic changes that we at Workiva (very large industrial user of dart) consider to be a good idea.

### CODE REVIEW

**Comment by aaronstgeorge-wf** [comment]
@jeking3 you helped a colleague of mine out on here https://github.com/apache/thrift/pull/1617, any chance you could help me get this in? The remaining failures are in erlang so I don't think anything in this change-set is responsible.

**Review by ulidtko — APPROVED** [review]
LGTM. All the changes make total sense when checked against Dart's 2.0.0+ [CHANGELOG](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md).

P.S: I've only worked with server-side Dart a little. Far from expert in it. However the PR makes sense generically anyway.

**Review by robbecker-wf — APPROVED** [review]
+1 Changes are what we've been running with on our own Workiva fork and are now being shared back to the main fork.
- removed new operators
- use overrides where needed
- ran dart format under dart 2+
- adjustments to run under dart 2+

**Comment by aaronstgeorge-wf** [comment]
@jeking3 or @Jens-G what could I go to get this branch moving? The remaining CI failures are in Erlang and I'm relatively certain were not caused by this change set.

**Comment by aaronstgeorge-wf** [comment]
Thanks @Jens-G !!

**Pull request closed without merging**
