### PR TITLE
Is tornado server not support TMultiplexedProtocol?

### PR DESCRIPTION
**Pull request by nxgych**
Is tornado server not support TMultiplexedProtocol?

### CODE REVIEW

**Comment by jeking3** [comment]
@jfarrell I think this can be closed; if folks need to ask a question you can do it on the developer's mailing list or open an Apache Jira ticket against the thrift project as a question.

**Comment by nxgych** [comment]
I have tested TMultiplexedProtocol for tornado, but it fails.

**Comment by jeking3** [comment]
Okay, but this pull request is still invalid.  We don't want to merge 0.9.3 into master.  Did you mean to open an Apache Jira question ticket instead of a pull request?

**Comment by nxgych** [comment]
OK, i will close this pull request, by the way, could you tell me when are you going to merge? next version?

**Comment by jeking3** [comment]
Going to merge what?  There's no need to merge branches into master.  The only unique changes in the branches is the version numbering.

**Comment by nxgych** [comment]
I mean that TMultiplexedProtocol not support tornado by testing result and i thought this problem have sovled in branch project.
Thank you!  I should submit this problem on Apache Jira.

**Pull request closed without merging**
