### PR TITLE
Trying out the Travis CI beta setup

### PR DESCRIPTION
**Pull request by joshk**
Sorry for the noise, but this project looks like a good candidate for helping us test out our new setup we are working on.

Please do not merge this in.

### CODE REVIEW

**Comment by jfarrell** [comment]
Hey @joshk, would love to get to a dockerized build in travis for testing so we can mirror our test env anywhere (currently having to duplicate setup in .travis.yaml and in dockerfiles is not ideal). What are the new beta setup capabilities?

**Comment by joshk** [comment]
This new setup will allow you to use Docker in your builds, is that something you are interested in?

**Comment by jfarrell** [comment]
yes, if we can get into the beta that would be great. our dockerfile that .travis.yaml mirrors from is build/docker/ubuntu/Dockerfile

**Comment by joshk** [comment]
So just to confirm, you just want to be able to use Docker within your build?

For now you can just do what I do in this PR, this will send you to the new stack which has Docker reinstalled.

**Comment by joshk** [comment]
@jfarrell hey, I was just wondering, all the failures, are they expected?

**Comment by joshk** [comment]
Hey @jfarrell, so I took a few stabs to see if I could get more of your build green, and I don't think I can by myself.

I would really love your help in getting this green so we can then compare this build to your master build. 

To note: this build is running on Trusty, so some packages may be different. You have 4 CPUs and around 15gigs of ram, but don't rely on this being the final config. And please don't merge in yet.

Thanks a bundle

**Comment by jfarrell** [comment]
hey @joshk, i'm testing the docker build now with the following. We are looking to simplify this process with our next release, but currently the main tests can be run with

```
docker build -t thrift build/docker/ubuntu
docker run -it --rm -v $(pwd):/thrift thrift /bin/bash -c "cd /thrift && ./bootstrap.sh && ./configure && make check"
```

**Comment by joshk** [comment]
@jfarrell have you tried this on Travis yet? I would love to see how this works and performs.

**Comment by jfarrell** [comment]
I have not tried this out yet, this has been one of the longer lagging issues I would love to address, but travis not supporting docker has been a blocker until now. I am preparing for a release candidate now and will plan on investing some time into fully testing this out in one of my branches. appreciate your help and also making docker support a direct possibility in travis

**Comment by joshk** [comment]
It is my pleasure, and there is more goodness to come!

**Comment by jfarrell** [comment]
This is now publicly available, closing test pr

**Pull request closed without merging**
