### PR TITLE
THRIFT-5410 CL build broken: Component :NET.DIDIERVERNA.CLON.TERMIO not found

### PR DESCRIPTION
**Pull request by m-g-r**
fixes [THRIFT-5410](https://issues.apache.org/jira/browse/THRIFT-5410): "CL build broken: Component :NET.DIDIERVERNA.CLON.TERMIO not found"
and makes `make check` work again with cl included.

tested with configure called as `./configure --with-ruby=no --with-php=no --with-nodejs=no --with-cpp=no --with-python=no --with-kotlin=no` to test only cl as the others would not work on my system or take really long.

had to revert:
1. Revert "THRIFT-5501 Remove Common Lisp support"
    This reverts commit d88d4f93b3390989bd47a43f3941ca7d576750f6.
2. Revert "THRIFT-5567: remove cl namespace references (#2580)"    
    This reverts commit 45471decdf572156189e66db59c8a1e82085299f.

### CODE REVIEW

**Comment by Jens-G** [comment]
> This branch cannot be rebased due to conflicts

Anything we can do about that?

**Comment by m-g-r** [comment]
> This branch cannot be rebased due to conflicts

Could you tell me where and when you get this error?

On this page I only see: "This branch has no conflicts with the base branch" and on the checks page it reads: " Mergeable / Mergeable succeeded 12 hours ago ".

**Comment by Jens-G** [comment]
> Could you tell me where and when you get this error?

On this page. Not sure if you can see it as well, since you may not have the necessary permissions.

image

**Comment by m-g-r** [comment]
Maybe you want to do the two reversions in a different pull request? Then this can be rebased... but I see no need for it and suggest to use "Create a merge commit" approach.

This PR contains the revert as well as asked for in https://issues.apache.org/jira/browse/THRIFT-5410?focusedCommentId=17584163&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17584163

From my perspective this is done. If there is another problem with the lisp backend, you can write me to have a look.

Cheers, Max

**Comment by Jens-G** [comment]
> From my perspective this is done. 

Agree.

> If there is another problem with the lisp backend, you can write me to have a look.

Good to know.

**Pull request closed without merging**
