### PR TITLE
Microsoft .Net Core library port and generator for this library 

### PR DESCRIPTION
**Pull request by vgotra**
Here is port of csharp library to .Net core and also generator for it (t_netcore_generator.cc)

All information in README.md files in subfolders with source code and samples.

### CODE REVIEW

**Comment by Jens-G** [comment]
Could you please file a JIRA ticket according to our [contrib guidelines](http://thrift.apache.org/docs/HowToContribute)?

**Comment by Jens-G** [comment]
### General

All code files etc. need an ASF header on top. Please have a look at the existing code if you are unsure, what, where and how to apply.

### using Serilog;  

We don't like external dependencies that much. Thrift supports about 20+ languages and dialects, each additional dependency has the potential to quickly become a PITA. So we avoid them wherever possible.

### lib/netcore/src/Samples

If that is the Thrift Test Suite client/server pair, that part should be move to /test/netcore. All other tests should remain under /lib/netcore. In addition to that, we have a [standardized set of arguments and exit codes](https://thrift.apache.org/test/). I haven't checked how close these program(s) already adhere to them, but from a first quick glance it may not 100%. 

### Compatibility I

Have you tested the code against at least one other language, preferably C++, Java or C#?

### Compatibility II

Can at least the Thrift Test Suite .NET Core Application  code be built on Linux and/or Mac? 

### AssemblyInfo.cs

Should be set up according to the existing C# code.

### /lib/netcore/src/Samples/.../Calculator.cs

The Tutorial code belongs under /tutorial/netcore. The code is later to be [included on the web site](https://thrift.apache.org/tutorial/) automagically from that folder. 

Next, generated code should generally not be put into the source tree. Part of the tutorial is to create these files from the IDL file.

### Summary

Great work, looks promising! But as I said, only a first look, however still plenty of room for improvement ;-) Have you seen [that document](https://thrift.apache.org/docs/HowToNewLanguage)?

**Comment by vgotra** [comment]
Hi - here is Jira Ticket for this new feature 
https://issues.apache.org/jira/browse/THRIFT-3933

**Comment by vgotra** [comment]
@Jens-G - about your comments:

> General
> 
> All code files etc. need an ASF header on top. Please have a look at the existing code if you are unsure, what, where and how to apply.

Done in the latest commit

> using Serilog;
> 
> We don't like external dependencies that much. Thrift supports about 20+ languages and dialects, each additional dependency has the potential to quickly become a PITA. So we avoid them wherever possible.

Removed in the latest commit

> lib/netcore/src/Samples
> 
> If that is the Thrift Test Suite client/server pair, that part should be move to /test/netcore. All other tests should remain under /lib/netcore. In addition to that, we have a standardized set of arguments and exit codes. I haven't checked how close these program(s) already adhere to them, but from a first quick glance it may not 100%.

Moved it to tutorial/netcore folder 

> Compatibility I
> 
> Did you test the code against at least one other language, preferably C++, Java or C#?

Yes, I tried to do that with Python (you can check README.md for Samples in tutorial/netcore folder). Tests completed without problems.

> Compatibility II
> 
> Can at least the Thrift Test Suite .NET Core Application code be built on Linux and/or Mac?

Without any problems - main library (Thrift for .Net Core automatically will be crossplatform)
You can build Samples for different platforms (I added 3 main platforms for Samples) and tested them on different OS (Win/MacOs/Ubuntu)
Example: 
dotnet restore
dotnet build **/*/project.json -r win10-x64 
dotnet build **/*/project.json -r osx.10.11-x64 
dotnet build **/*/project.json -r ubuntu.16.04-x64 

> AssemblyInfo.cs
> 
> Should be set up according to the existing C# code.

Done

> /lib/netcore/src/Samples/.../Calculator.cs
> 
> The Tutorial code belongs under /tutorial/netcore. The code is later to be included on the web site automagically from that folder.

Done

> Next, generated code should generally not be put into the source tree. Part of the tutorial is to create these files from the IDL file.

It can be complex part - because this IDL should be created with new Thrift generator (which should include functionality for .NET Core generation)

**Comment by Jens-G** [comment]
Hi,

> > >  lib/netcore/src/Samples
> > >
> > If that is the Thrift Test Suite client/server pair, that part should be 
> > move to /test/netcore. All other tests should remain under /lib/netcore. 
> > [...]
> >
> Moved it to tutorial/netcore folder
>

Yes, cool, thanks, but ... we do have something (i.e. an incarnation of the 
Thrift Test suite client/server pair) to put under /test/netcore, do we?

The general idea is such:
- the /test folders house the Thrift Test suite client/server pairs
- the /tutorial folders is what later appears on the web site under 
Tutorials. This is the Calculator example.



> > generated code should generally not be put into the source tree. Part of 
> > the tutorial is to create these files from the IDL file.
> >
> It can be complex part - because this IDL should be created with new 
> Thrift generator (which should include functionality for .NET Core 
> generation)
>

The Thrift compiler must always match the the library code nevertheless. 
This is a given, doing otherwise will lead to problems, because things 
change between versions. Hence the generated code comes with the implicit 
assumption of being linked against the library version that matches the 
Thrift compiler used. Always.

Second, creating the code from the IDL is (or should be) as simple as

    $ thrift  -r  -gen netcore   Tutorial.thrift

There is nothing complicated or complex about it, and it should not be more 
complex than that.


Have fun,
JensG

**Comment by vgotra** [comment]
@Jens-G - Updated  (added tests). Not sure how to run tests with test.py (just updated tests.json) - it seems that you have custom configuration for running tests. Manually executed tests (server and client) - http://prntscr.com/crl5km.

There is still an issue with including of generated files on prebuild action (it's related to cli tools - dotnet cli ). It can be easily fixed after merging netcore changes to thrift generator and adding additional cmd line for generation code from idl before building tests and running them with test.py.

You can run them in easy way for check - install dotnet sdk (https://www.microsoft.com/net/core#windows) for your platform and then run "dotnet restore && dotnet run server" and "dotnet run client"

**Comment by Jens-G** [comment]
@vgotra: Thanks, not forgotten. I'll look into it after the 0.10.0 release happened, so please stay tuned.

**Comment by BlacKCaT27** [comment]
@Jens-G is there likely going to be any movement on this PR soon? I'd really love to use thrift with .net core and would prefer to do so using the main thrift branch when feasible. I can use @vgotra 's fork in the mean time, but curious when you think this will be available to general thrift users.

**Comment by Jens-G** [comment]
Yes, only a matter of (available) time.

**Comment by Jens-G** [comment]
(1) The Generator file is in the wrong path
(2) What is all that stuff under '''lib\netcore\src\Tests\Thrift.PublicInterfaces.Compile.Tests\Generated''' for? Why do we want to put generated stuff into the repo?

**Comment by Jens-G** [comment]
(3) The *.thrift sources should not be duplicated under `tutorial\netcore\Interfaces`

**Comment by BlacKCaT27** [comment]
Another issue I noticed with this PR, and this could well be me having done
something wrong, but I was only able to find one set of thrifts typical
classes (processors, servers, etc). Meaning unless I wanted to use those
specific configurations (async using json), I was out of luck on .net core.

Did I miss something or is this actually the case?

If so, shouldn't there be tests that check for this? There should be tests
that can ensure each type of processor/server/etc can be instantiated.

**Comment by Jens-G** [comment]
@BlacKCaT27: This is Github, you can always send a PR to @vgotra. I already did that.

**Comment by Jens-G** [comment]
@vgotra: I'm about to clean up the patch. Since in the current state it very likely will not build and you seem to have little time right now, I started work [over here](https://github.com/Jens-G/thrift/tree/haxe) to bring your PR in a form ready to be merged. I'd love to see this become part of Thrift but there is some work to do, so let's do it.

**Comment by vgotra** [comment]
@Jens-G - Hi Jens. 

I added changes for netcore implementation in the latest fork of Thrift repo (https://github.com/vgotra/thrift): 
- migration to csproj from project.json (https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/)
- update to latest .NET Core framework (netcoreapp1.1)
- added implementation of framed transport
- added info how to build Thrift IDL with VS2017 RC
- other minor changes

There is still problems with .NET Core CLI tools - they fixed problem with restore, but console build of solution with library based on .NET standard 1.6 and console app based on netcoreapp1.1 can cause problems.

MS planned to release NET Standard 2.0 in Q1 2017 (https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/). 

I can wait for official release and then update everything to official stable version and create create pull request - or update docs and create new pull request with current changes to include them into the next release of Apache Thrift.

Please, let me know your thoughts about that.

Thanks

**Comment by Jens-G** [comment]
The first thing I noticed is that there are a bunch of one-line changes where an UTF-8 BOM has been added to certain files. Not that I'm against it, but can we at least have it consistently? E.g. TSocketClientTransport.cs has a BOM, but TBufferedClientTransport.cs has not. Minor issue only.

**Comment by Jens-G** [comment]
I can't get it to work. The most recent build I found for Windows is telling me
```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

```
But build.cmd fails with 
```
warn : The folder 'E:\D\TPCPP\Thrift\wc-XE-all\wc-JensG-haxe\tutorial\netcore' does not contain a project to restore.
Couldn't find 'project.json' in current directory
Couldn't find 'project.json' in current directory
Couldn't find 'project.json' in current directory
```

Linux not tried yet.

**Comment by vgotra** [comment]
Hi @Jens-G 

You can use .NET Core SDK 1.0 Preview 4 build 004233 (https://github.com/dotnet/core/blob/master/release-notes/preview4-download.md) - this package supports new csproj format for building apps.

That's why I still waiting before creation of pull request.

I updated https://github.com/vgotra/thrift/blob/master/lib/netcore/README.md for new csproj format. But not updated build scripts fully.

**Comment by Jens-G** [comment]
Could you extract the other stuff (e.g. framed transport, multiplex, ...) into a separate PR that works with the current Thrift code base? Smaller PRs are easier to review, and we get at least these changes in early.

**Comment by vgotra** [comment]
Yes - I can. Not sure about multiplex. I will check it and ping you later.

**Comment by vgotra** [comment]
Hi @Jens-G 

Done - you can check master in https://github.com/vgotra/thrift.

Added framed transport and added sample of usage of MultiplexedProtocol. Also updated docs for library.

I matched that last time you used 1.0.0-preview2-1-003177 version of .Net Core SDK - you can also experiment with different SDK of .Net Core (just change version of SDK in solution global.json - I added samples). 

The only thing - in 1.0.0-preview2-1-003177 version of .NET Core CLI, dotnet doesn't support simple passing of arguments. So, for correct work of tutorial, arguments should be passed to cmd for server and client in full form like a (dotnet run -t:tcp -p:multiplexed, dotnet run -help). In latest SDK of .NET Core CLI added possibility to use passing arguments in more easy way - like: dotnet run -- -p:multiplexed, dotnet run -- -h

Pls, ping me when you will be ready to merge pull request and I will create it.

**Comment by Jens-G** [comment]
> Pls, ping me when you will be ready to merge pull request and I will create it.

Make the PR when you think it's ready. I'll find some spare time. We will not have that many merge conflicts to solve with the netcore stuff right now.

**Pull request closed without merging**
