### PR TITLE
Review for pull up of RUST extended namespace support, addition of macros to allow application to macroize over defintions ...

### PR DESCRIPTION
**Pull request by przygienda**
Please review initial request here ...

### CODE REVIEW

**Comment by przygienda** [comment]
OK, finished. The patch does 

* improve the namespace support by allowing to nest Thrift models inside a package now
* moves the reading/writing into a proper trait so models can be differentiated and generics written over them
* adds macro definitions to all generated types which allows the package generating the code to e.g. generate code over model definitions, e.g. to derive custom traits via macrosthat use the internal structure of enum/struct/union such as custom defaults, statistics and so on ...

**Comment by jeking3** [comment]
Is there an Apache Jira ticket associated with this pull request?  I know there have been a number of folks working on RUST support.  Given the size of this, it needs reviews and it also needs to get committed so it doesn't gather conflicts over time.

If there is no Jira ticket for it yet, if you could create one that would be great.

https://thrift.apache.org/docs/HowToContribute

**Comment by jeking3** [comment]
@allengeorge would you agree we should close this pull request and tackle each item individually per the open Jira items?

**Comment by allengeorge** [comment]
Yes please - that would be the best course of action.

**Comment by jeking3** [comment]
If @przygienda could close it, that would be great.

**Comment by przygienda** [comment]
Our MailScanner believes that the attachment to this message sent to you

**Comment by jeking3** [comment]
@jfarrell this can be closed.

**Comment by przygienda** [comment]
Thanks for closing, yes, the work moved to main thrift tracker ...

**Pull request closed without merging**
