### PR TITLE
The SSL authentication fails in the Java test of the CI.

### PR DESCRIPTION
**Pull request by zeshuai007**
- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [ ] Did you squash your changes to a single commit?  (not required, but preferred)
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by zeshuai007** [comment]
Hi,

After many tests (each time waiting for CI execution is too long, which is equivalent to a basketball game), this problem has been determined to be a cross-language SSL communication test between a Java service and an erlang client, because erlang is not familiar to me, and I carelessly ignored it earlier. 
Now, I only add the keystore and truststore to java-test and quickly check the test_client of Erlang. For --ssl, there are ssltransport and certificate. Next, I need to confirm the protocols on both sides. Has anyone investigated the CI problem? 
Any help is welcome.

**Comment by ulidtko** [comment]
Hi @zeshuai007 — I was looking if anyone has done anything to fix this thing on Travis:
```
===============================================================================
*** Following 6 failures were unexpected ***:
If it is introduced by you, please fix it before submitting the code.
===============================================================================
server-client:          protocol:         transport:               result:
java-erl                multi-binary      fastframed-framed-ip-ssl failure(1)
java-erl                multi-binary      buffered-ip-ssl          failure(1)
java-erl                multi-binary      framed-ip-ssl            failure(1)
java-erl                binary            fastframed-framed-ip-ssl failure(1)
java-erl                binary            buffered-ip-ssl          failure(1)
java-erl                binary            framed-ip-ssl            failure(1)
===============================================================================
```

And I see you added explicit truststore support in the `Test{Client,Server}` for Java. Do you need the same for Erlang?

**Comment by zeshuai007** [comment]
Hi @ulidtko 
Sorry we didn't get updates in time. 
This problem is caused by the communication authentication failure between the Java server and Erlang client. The cause has been found out.
The Erlang community released OTP-23 in May this year. This version has major changes that damage compatibility. SSL3.0 is abandoned and TLS1.3+TLS1.2 is used by default. However, the Java server uses TLS1.2 by default and does not support TLS1.3. Therefore, the Travis-CI integration test has not been working properly since the end of May. 
For now, I think a feasible solution is available. 
1. By default, Travis-CI uses the latest Erlang version for integration tests. It may be set to OTP-22. After all, the Erlang version 22 is also specified on the readme. 
2. Upgrade JDK8 to JDK11. TLS1.3 is supported by default. 
3. The TLS1.3 protocol can also be supported on JDK8. That's what I've been working on.

**Comment by ulidtko** [comment]
Hi @zeshuai007 

>  SSL3.0 is abandoned

That's a good update.

> and TLS1.3+TLS1.2 is used by default. However, the Java server uses TLS1.2 by default and does not support TLS1.3.

This gives me doubt about whether the root cause was identified correctly and precisely. TLS protocol, just like every other good protocol, has versions, and allows both the client and the server to support multiple versions. As long as the Java server speaks TLS1.2, any client which speaks TLS1.2 should be able to connect — regardless of TLS1.3.

> The Erlang community released OTP-23 in May this year.

BTW, last successful build of `master` on Travis is **7 months** old. I am in doubt whether Erlang update is really relevant. But I understand that it certainly makes finding the real root cause more complicated.

> It may be set to OTP-22.
That's not a good idea. It will only entrench the stagnation and multiply the effort to update for the next engineer.

**Comment by ulidtko** [comment]
Whew, what a ride! Diving into Erlang is joy.

I did a bit of testing on this... Except for the fiddly setup and a few deprecation-updates needed, the Erlang library looks mostly functional. All unit-tests under `lib/erl/test` pass (well, after you've had enough fun with the setup required to run them).

I also run the Erlang client on **OTP 23** against some implementations, including the Java server from the cross-test suite. Findings:
 * The Erlang client does connect to `openssl s_server` using TLS1.2.
 * The Erlang client does connect to `openssl s_server` using TLS1.3.
 * The Erlang client does connect to `openssl s_server` using TLS1.2 with client cert required (`-Verify 2`).
 * The Erlang client does connect to `openssl s_server` using TLS1.3 with client cert required (`-Verify 2`).
 * The Erlang client **does not** connect to `socat - openssl-listen:9008,cert=test/keys/server.pem,cafile=test/keys/CA.pem` despite using the very same OpenSSL; error produced:

       socat[1847925] E SSL_accept(): error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed

   I tend to think it's a bug in how `socat` instructs the openssl API to verify client certs. Didn't investigate this deeper.

 * The Java cross-test server [on git master] claims to only support **TLS1.3**: 
 image

   Which is [really really weird](https://blog.cloudflare.com/why-tls-1-3-isnt-in-browsers-yet/). I'm not sure this is intentional. Somebody needs to check this. @zeshuai007 please see above; bytes on the wire directly contradict your claim *"the Java server uses TLS1.2 by default and does not support TLS1.3"*. It shows the opposite: TLS1.3 *only* is advertised by the Java server. I'm running `openjdk version "11.0.8" 2020-07-14`.

 * You can run a section of the Thrift cross-test suite (a.k.a. "Apache Thrift - Integration Test Suite") directly:

       ./test.py --server java --client erl --regex ip-ssl
   
    This runs in ~20 seconds. Still way faster than waiting many basketball games for Travis to run it. :wink: 

 * Finally: the TLS 1.3 connection from Erlang client to Java server **does not** go well indeed. Here's a debug dump from Erlang side: [java-erl-tls1.3_client.log](https://github.com/apache/thrift/files/5048136/java-erl_binary_buffered-ip-ssl_client.log). It appears that the Java server is doing something that makes the Erlang client crash :/

    Anyhow, **all tests pass** if I restrict Erlang to only TLS 1.2 & TLS 1.1:
    ```
    ulidtko@pasocon ~/s/t/test (master)> ./test.py --server java --client erl
    Apache Thrift - Integration Test Suite
    Sun Aug 09 20:37:26 2020
    ===============================================================================
    server-client:          protocol:         transport:               result:
    java-erl                binary            buffered-ip              success
    java-erl                binary            fastframed-framed-ip     success
    java-erl                binary            framed-ip                success
    java-erl                binary            fastframed-framed-ip-ssl success
    java-erl                binary            framed-ip-ssl            success
    java-erl                binary            buffered-ip-ssl          success
    java-erl                multic-compact    framed-ip                success
    java-erl                multic-compact    buffered-ip              success
    java-erl                multic-compact    framed-ip-ssl            success
    java-erl                multic-compact    buffered-ip-ssl          success
    java-erl                multic-compact    fastframed-framed-ip     success
    java-erl                multic-compact    fastframed-framed-ip-ssl success
    java-erl                multi-binary      framed-ip                success
    java-erl                multi-binary      buffered-ip              success
    java-erl                multi-binary      fastframed-framed-ip     success
    java-erl                multi-binary      framed-ip-ssl            success
    java-erl                multi-binary      buffered-ip-ssl          success
    java-erl                multi-binary      fastframed-framed-ip-ssl success
    java-erl                compact           framed-ip                success
    java-erl                compact           framed-ip-ssl            success
    java-erl                compact           buffered-ip              success
    java-erl                compact           fastframed-framed-ip     success
    java-erl                compact           buffered-ip-ssl          success
    java-erl                compact           fastframed-framed-ip-ssl success
    ===============================================================================
    No unexpected failures.
    ```
    ... Which is be done by passing `-ssl protocol_version "['tlsv1.2', 'tlsv1.1']"` to the `erl` invocation.

---------------------

Amusingly, the very same Java server which says it only speaks TLS1.3 to TLS1.3 clients — suddenly starts talking TLS1.2 just fine, to a non-tls13 client. What a mess!

**Comment by zeshuai007** [comment]
Hi @ulidtko 
I'm not sure whether this is a new issue. 
The Java8 server supports only TLS1.2. When negotiating with the Erlang client over the TLS protocol, the Java8 server does not support TLS1.3. I think we should revert to the actual scenario because JDK8 was used in the Tranov-ci integration test. Can you use JDK8 to retest it? 

Cheers, 
Zezeng Wang

**Comment by ulidtko** [comment]
Hi @zeshuai007 — well, that totally makes sense.

I retested with Java 8 (OpenJDK as before).

The result with Java8 (for `test.py --server java --client erl` only) is **success of all tests** for me. Both with TLS1.3 allowed and disallowed for the Erlang client — the java server doesn't offer TLS1.3, exactly as you say; so it just negotiates down to TLS1.2, and all proceeds well from there.

Which is a puzzling result. I remember seeing this failure on Travis — but can no longer find any build exhibiting it. Do you perhaps have a link to such a build on Travis?

I did found [one](https://travis-ci.org/github/apache/thrift/jobs/665484688) from March 22, which has reached running the `cross` step — and had passed all of it (log line 21337 onwards). Notice (log line 13268) that it used Java 11!

That confused me at first, since Java11 + Erlang23 = TLS1.3 = broken according to my testing, should not have passed — but as you mention, Erlang/OTP 23 was only released in May, later than the build I linked.

What makes you think that Java 8 is in use? Can you find a failed build with Java 8 on Travis?

**Comment by ulidtko** [comment]
Just to keep track of things:
 * I minimized the TLS 1.3 handshake failure against Java 11 — filed as https://bugs.erlang.org/browse/ERL-1331
 * The issue can be temporarily worked around by adding `"-ssl", "protocol_version", "['tlsv1.2', 'tlsv1.1']",` to the Erlang client commandline in `tests.json` — this disables TLS1.3 on Erlang side and then all `java-erl` cross-tests pass.

**Comment by zeshuai007** [comment]
Hi @ulidtko   

I didn't investigate the CORSS run you found on March 22, but in all the compilation builds on Travis, I compared the last successful run log of erlang22 jobs to the last failed run log of erlang23, so I'm sure, this problem is caused by the upgrade to erlang23. 
Travis-CI: 
erlang22 - Last successful ([build#6701](https://travis-ci.org/github/apache/thrift/builds/692484717)) 
https://travis-ci.org/github/apache/thrift/jobs/692484722 
erlang23 - First execution failed ([build#6702](https://travis-ci.org/github/apache/thrift/builds/692597055 )) 
https://travis-ci.org/github/apache/thrift/jobs/692597058 
Note that log line 13101 uses jdk11, and JAVA_HOME set in log line 12340 is java-8-oracle (Java JVM running environment, so I think Java8 is used actually). 
Therefore, erlang-client uses TLS1.3 (Erlang23 supports two TLS versions, which seems to be a feature of the new Erlang version) and Java-server (JDK11/TLS1.3) / (JDK8/TLS1.2). 
Thank you for your work. If there is no better solution, setting up TLS1.2+TLS1.1 temporarily will look great as setting up Erlang22, but it will require two or more post-maintenance. I saw the ticket you submitted in Erlang, and I look forward to the Erlang expert's investigation. 
I have plans to learn Erlang recently, and unfortunately for some reason I'm focusing on C, but I'll be back. 

Cheers, 
Zezeng Wang

**Comment by ulidtko** [comment]
> JAVA_HOME set in log line 12340 is java-8-oracle

Okay, I understand now. Let me convince you that this is noise and Java8 is not actually used. Two reasons:
 * This line 12340 is part of output from `printenv | sort` from `build/docker/run.sh`: it shows the `JAVA_HOME` environment variable set **outside** the Docker container. It's not existing *inside* the container where `./configure` and tests run.
 * If it was — we'd see *Oracle* JDK 8, not OpenJDK, in the output of `./configure` (line 13101).

I'm glad to collaborate for the public good and for safe and sustainable future of technology. Thanks for your responses, effort and friendliness in this space, Zezeng Wang, this is deeply appreciated.

**Comment by ulidtko** [comment]
Heads up about the [Erlang TLS 1.3 issue][•]:
 1. This is a known bug;
 2. It is already fixed, but isn't released yet;
 3. OTP 23.1 is planned for release in September, and will contain the fix for TLS 1.3;
 4. OTP 24 is planned for release on a yearly timescale, and will contain the fix too.

[•]: https://bugs.erlang.org/browse/ERL-1331

**Comment by zeshuai007** [comment]
This PR resolves the CI issue caused by the upgrade from Erlang23 to TLS1.3. This issue has been resolved in OPT23.1 [https://bugs.erlang.org/browse/ERL-1331]. Therefore, I close this PR.
It should be noted that the current CI issue is a rebar3 issue and should be tracked on other tickets.

**Pull request closed without merging**
