### PR TITLE
Thrift 3839

### PR DESCRIPTION
**Pull request by kufd**

### CODE REVIEW

**Comment by sstach** [comment]
Is there a chance that the build failures get fixed soon? We are facing the same problem and this fix would be awesome if it works as mentioned!

**Comment by kufd** [comment]
We use this fix in our prod and it works as mentioned.

But as i can see the build is failed not because of my changes
So i am just waiting for review from commiters.

**Comment by jeking3** [comment]
Please rebase your pull request against origin/master.  The build may not be 100% stabilized but we removed the offending Jenkins build that was constantly failing.  2 out of my 3 open pull requests passed Travis and AppVeyor once I did this. :)

**Comment by kufd** [comment]
I have merged changes from original thrift repo
But problems are still present
One  travis job is failed because of timeout
AppVeyor is not finished yet
Should i merge changes again?

**Comment by jeking3** [comment]
Yes, continue to rebase against master and force push until it passes; if there are no changes to pick up add an extra blank line to the end of one of the files, commit, rebase/fixup and force push.  That will kick another build.  We do have builds passing now (not 100% - there are still environmental issues, but we're getting better).

**Comment by kufd** [comment]
Done

**Comment by sstach** [comment]
@asfgit Why did you closed the PR?

**Comment by nsuke** [comment]
@sstach it's closed because it's merged to the master  dd9885e

**Comment by sstach** [comment]
Oh, have overseen that, thanks.

**Pull request closed without merging**
