### PR TITLE
THRIFT-5197: TSSLTransportFactory Buries NOT_OPEN Exception Type for …

### PR DESCRIPTION
**Pull request by belugabehr**
…Client

  

- [X] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [X] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [X] Did you squash your changes to a single commit?  (not required, but preferred)
- [X] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [X] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by Jens-G** [comment]
Looks good to me. I always wondered if we should forbid throwingsuch kind of exeptions without error code at all. The error code should be mandatory. Personal opinion of course.

**Comment by belugabehr** [comment]
Might also be nice to have subclasses instead of having to pass a number into the constructor manually.

**Comment by belugabehr** [comment]
And for completeness sake, I came across this issue using Hive's 'beeline' utility.  It's a lightweight SQL client that ships with Apache Hive.  During an SSL initialization error, I was getting an "unknown error" message,... which was less than helpful. :)

https://github.com/apache/hive/blob/c3007d497ca58c595da8bd78455538a1ce0e3485/beeline/src/java/org/apache/hive/beeline/BeeLine.java#L2180-L2182

**Comment by belugabehr** [comment]
Thanks for the review @Jens-G 
Can you please help me get this merged?

**Pull request closed without merging**
