### PR TITLE
[c_glib] Fix a warning and incorrect error message

### PR DESCRIPTION
**Pull request by kainjow**
Fixes to the warnings seen below with clang from Xcode 11. Also fixed a log.

> /lib/c_glib/src/thrift/c_glib/transport/thrift_ssl_socket.c:273:12: Unused variable 'retval'

> /lib/c_glib/src/thrift/c_glib/transport/thrift_ssl_socket.c:275:11: Unused variable 'rc'

- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?  (not required for trivial changes)
- [ ] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, add ` [skip ci]` at the end of your pull request to free up build resources.

### CODE REVIEW

**Comment by jeking3** [comment]
Looks good to me; note until I get CI working again for erlang and rust, I'm trying not to merge too much, so if there's a delay that's why.

**Comment by jeking3** [comment]
Please rebase on master to clear up most of the Travis CI issues.

**Comment by Jens-G** [comment]
@kainjow: Possible to rebase against current master?

**Comment by Jens-G** [comment]
ping

**Comment by kainjow** [comment]
Yes I will.

**Comment by kainjow** [comment]
@Jens-G @jeking3 backed out some changes which were causing the tests to fail that I don't understand yet, now it's simpler and passing.

**Comment by Jens-G** [comment]
@kainjow While trying to merge I ran into conflicts. Could you squash all of your commits into one and rebase again? I'll take care of it then ASAP.

**Comment by kainjow** [comment]
> @kainjow While trying to merge I ran into conflicts. Could you squash all of your commits into one and rebase again? I'll take care of it then ASAP. Sorry for the delay.

yes I can. Is squashing in a PR necessary? Shouldn't the repo be configured to only allow squash merges? IMO squashing review commits makes it harder to see what is changed.

**Comment by Jens-G** [comment]
> I can merge master. 

Well, above there is an message saying "This branch cannot be rebased due to conflicts". If it works for you - congratulations! But that's not what counts here. 

> Is squashing in a PR necessary? [...] 
> IMO squashing PR commits makes it harder to see what is changed during review.

If it helps you to stay productive and efficient during review, do as you like. It will be squashed anyway. Just as a general rule of thumb: If any change set is too large to be reviewed, that could be an indicator that there may be more fundamental problems with it.

The key point here is the merge, since nobody will resolve your conflicts for you. I apologize again for the delay with this PR, that's on us. Let's pull up sleeves and get it done together.

**Comment by kainjow** [comment]
It appears there are no conflicts now. I see "This branch has no conflicts with the base branch".

**Pull request closed without merging**
