### PR TITLE
THRIFT-2835 Add possibility to distribute generators separately from thr...

### PR DESCRIPTION
**Pull request by nsuke**
...ift core, and load them dynamically

### CODE REVIEW

**Comment by jeking3** [comment]
Lots of work in here!  You might want to close and re-open this pull request to kick a new build.  It needs to pass CI before anyone can merge it.

**Comment by nsuke** [comment]
Hi, you're so diligent :)
It's quite old so I'll rather rebase it.

**Comment by jeking3** [comment]
The pull request list would be a lot easier to manage if it was always clean/empty, so I want to work towards that.

**Comment by nsuke** [comment]
I rebased it to the current master.
The original first commit is extracted as THRIFT-3138 (ef0a8fa62a8a86b23999f9a9ad31478852474854) because it was an unrelated issue.
The other commit remains strictly unchanged except that I had to resolve several trivial conflicts in build scripts.

**Comment by nsuke** [comment]
TODO:
* Remove `sleep 0.2` in cpp_plugin_test.sh without breaking it
* Build with static boost unittest (need to do the same as some tests in lib/cpp/test)

**Pull request closed without merging**
