### PR TITLE
THRIFT-5600: upgrade rust toolchain to 1.61 and edition 2021 & THRIFT-5606: Wrong indent for const double

### PR DESCRIPTION
**Pull request by OmmyZhang**
I have tried to create pr for @Jimexist 's branch to fix pr #2632, but as there are too many changes, finally I decided to open a new pr to bump rust version and fix CI first.

for TRIFT-5606:

- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [ ] Did you squash your changes to a single commit?  (not required, but preferred)
  -  please use squash when finally merging it
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [x] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by OmmyZhang** [comment]
Now there are problems with Java. It seems that I should create a new Jira ticket.

**Comment by OmmyZhang** [comment]
for TRIFT-5606:

- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [ ] Did you squash your changes to a single commit?  (not required, but preferred)
  -  please use squash when finally merging it
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [x] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

**Review by Jimexist — APPROVED** [review]
would like @allengeorge to review as well before merging

**Comment by OmmyZhang** [comment]
@Jimexist thanks!

By the way, can I disable ssl test for java and create a jira, to fix CI? (Seems there are also other problems, not sure, just want to try

**Comment by Jimexist** [comment]
> @Jimexist thanks!
> 
> By the way, can I disable ssl test for java and create a jira, to fix CI? (Seems there are also other problems, not sure, just want to try

looks like a plan to me!

**Pull request closed without merging**
