### PR TITLE
 Fix condition where TSimpleServer could exit AcceptLoop() without releasing lock.

### PR DESCRIPTION
**Pull request by mdubbyap**
…easing lock

### CODE REVIEW

**Comment by dcelasun** [comment]
Thanks for the PR. Seems like this was [introduced](https://github.com/apache/thrift/blame/930428438c0b6c8f60560cbb7dcad79042badacb/lib/go/thrift/simple_server.go#L131) by THRIFT-4243 (PR #1302) and unfortunately made its way into the 0.11 release.

**Comment by dcelasun** [comment]
Travis failures are unrelated flaky tests (my own Travis build is fine).

**Comment by jeking3** [comment]
Thanks for checking, we need to stabilize these CI builds so less effort is spent figuring out if a change is at least somewhat ok.

**Comment by jeking3** [comment]
THRIFT-4537

**Pull request closed without merging**
