### PR TITLE
convert net order to host order for double type

### PR DESCRIPTION
**Pull request by philomely**
- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?  (not required for trivial changes)
- [ ] Did you squash your changes to a single commit?
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"

### CODE REVIEW

**Comment by jeking3** [comment]
This broke all the lua tests.  My take is that the fix is unnecessary, as the cross-language tests were working before this fix (and they test doubles), and now they are broken.

**Comment by philomely** [comment]
@jeking3 before the fix. lua version can't send double to java or c# correctly 'cause the order issue. not sure other tests

**Comment by jeking3** [comment]
Our cross language tests send doubles from lua client to java server and back:

java-lua                binary            framed-ip                success
java-lua                binary            buffered-ip              success

On the client lua side here is the code:
https://github.com/apache/thrift/blob/master/test/lua/test_basic_client.lua#L147

On the server java side here is the code:
https://github.com/apache/thrift/blob/master/lib/java/test/org/apache/thrift/server/ServerTestBase.java#L89

The reverse where Java is the client:
https://github.com/apache/thrift/blob/master/lib/java/test/org/apache/thrift/test/TestClient.java#L282

and lua is the server:
https://github.com/apache/thrift/blob/master/test/lua/test_basic_server.lua#L57

HOWEVER we do not seem to be running any tests where lua is the server.  That's a bug, but I still feel the round trip from lua client through java server disproves what you said.

Is there something deficient in these tests we're missing?  We are proving that doubles successfully round-trip with these tests.  Are we testing enough values and enough boundaries to prove or disprove what you are saying?

**Comment by jeking3** [comment]
Closing based on comments.

**Pull request closed without merging**
