### PR TITLE
WIP: THRIFT-5162: ThreadManager tests fail in appveyor

### PR DESCRIPTION
**Pull request by janosvitok**
Client: cpp
Server: cpp

Fix waiting in wait(), waitForTimeRelative, waitForTime, waitForever.
Introduce new field notified_ to avoid spurious wakeups of Impl::conditionVariable_

- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [x] If your change does not involve any code, add ` [skip ci]` at the end of your pull request to free up build resources.

### CODE REVIEW

**Comment by dcelasun** [comment]
@janosvitok any progress?

**Comment by janosvitok** [comment]
No. the code in PR causes deadlocks and I didn't have time to find out the problem, and I won't soon. Sorry.

**Comment by dcelasun** [comment]
No worries, please ping me whenever you are ready and I'll take a look.

**Comment by janosvitok** [comment]
I will not continue with this. Sorry.

**Pull request closed without merging**
