### PR TITLE
THRIFT-5215: Remove portable_endian.h

### PR DESCRIPTION
**Pull request by penenin**
Client: cpp

Remove portable_endian.h  

- [X] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [X] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [X] Did you squash your changes to a single commit?  (not required, but preferred)
- [X] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by penenin** [comment]
Is there a way to force the CI to rerun? One test failure is in netstd, another is in Java and the third looks like it might be transient since it was an iostream error. I would like to rerun that last test.

**Comment by janosvitok** [comment]
You may try 1) rebase branch on current master 2) push --force

**Comment by dcelasun** [comment]
I've restarted the CI build.

**Comment by emmenlau** [comment]
I'm also testing the branch over the weekend. Thanks for the quick response!

**Comment by penenin** [comment]
That time the failing test was because of a 504 on a git clone. (I believe it passed the first time.) I tried git push --force but it didn't seem to kick off the CI again. I am already up-to-date on master. I'll wait until the next commit and then rebase the branch again.

**Comment by dcelasun** [comment]
All tests are green!

**Comment by ulidtko** [comment]
To kick CI, just do empty `git commit --amend` followed by `git push -f`. This will modify dates of your HEAD commit, and therefore change the commit sha, and so will be seen as new content by CI bots.

**Pull request closed without merging**
