### PR TITLE
THRIFT-4531

### PR DESCRIPTION
**Pull request by margars**
I am not familiar with your rules for contributions. This issue is described in JIRA THRIFT-4531.

### CODE REVIEW

**Comment by dcelasun** [comment]
There are no changes in this PR. Please correct it and force push.

**Comment by margars** [comment]
Sorry, I am not familiar with all this setup and rules.

**Comment by dcelasun** [comment]
Also, please squash your commits.

**Comment by margars** [comment]
I am behind corporate firewall and don't know how to squash from the web interface, will try from scratch.

**Pull request closed without merging**
