### PR TITLE
Use platform executable suffix for thrift compiler

### PR DESCRIPTION
**Pull request by emmenlau**
This PR adds a trivial change. It appends `CMAKE_EXECUTABLE_SUFFIX` to the name of the thrift compiler. This adds i.e. `.exe` on Windows. While this is not strictly required, it can be helpful when building on Cygwin and/or MinGW due to their "hiding" of the `.exe`-suffix.

- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [x] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by Jens-G** [comment]
The errors seem not to have anything to do with it, but may I still ask to force-push again?

**Comment by emmenlau** [comment]
Yes good idea. Pushed again...

**Comment by emmenlau** [comment]
The build errors are now very likely unrelated. Please review and merge :-)

**Comment by emmenlau** [comment]
Thanks @Jens-G !

**Pull request closed without merging**
