### PR TITLE
THRIFT-4547: add swift to bionic build image and run unit tests

### PR DESCRIPTION
**Pull request by jeking3**
This is a prerequisite to writing and running swift clients and servers in the cross test.

### CODE REVIEW

**Comment by jeking3** [comment]
Sadly, it didn't actually run the swift unit tests.

**Comment by yurikoles** [comment]
@jeking3 is there a public CI BTW?

**Comment by yurikoles** [comment]
@jeking3 
```Detected docker stage build and no defined DOCKER_PASS, this build job will be skipped.```

**Comment by jeking3** [comment]
You can run the CI in your own fork.

**Comment by jeking3** [comment]
That's normal (build job will be skipped) that's just a docker image build job if needed.  The bionic build below didn't run the swift "make check".

**Comment by jeking3** [comment]
I had forgotten to add swift as a SUBDIRS entry in the lib/Makefile.am - I believe that's all set now.

**Pull request merged**
