### PR TITLE
Java generator: Added "java.lang." to all generated instances of type…

### PR DESCRIPTION
**Pull request by ne0h**
… java.lang.Object to enable the usage of "Object" as struct name in thrift.

### CODE REVIEW

**Comment by Jens-G** [comment]
Hi @ne0h,

could you just [create a JIRA ticket for this](http://thrift.apache.org/docs/HowToContribute)?

@Java devs: Comments anyone?

**Comment by ne0h** [comment]
Hi Jens-G,

of course: https://issues.apache.org/jira/browse/THRIFT-3954

**Comment by bgould** [comment]
@Jens-G 

IMO this is a valid use case but it is not necessarily a great idea because in general its not very user friendly to design an API that clashes names in java.lang.* ... it is even more complicated in Thrift because other languages may also have constructs called "Object" (javascript for example).  There is not a Java-specific technical reason why this shouldn't be allowed however.

That said, there is a related JIRA, not exactly the same problem because java.lang classes do not require import statements, but the idea is the same:

https://issues.apache.org/jira/browse/THRIFT-3301

**Comment by jeking3** [comment]
@bgould Generated code should always be explicitly fully pathed or namespaced and never make any assumptions.  Thrift already uses namespaces so I would have no problem with org.king.Object as a thrift structure so long as it derives from java.lang.Object.  If the code generator uses "Object" without qualifications that could be ambiguous, and that is a valid defect .. I like the idea of eliminating that.  With regards to using a structure named Object, well that's really up to the folks using thrift, it isn't up to the thrift project to tell them how to name their structures and we should stay out of their way where we can.

**Comment by bgould** [comment]
@jeking3 

I agree completely.  Didn't mean to give the impression that it shouldn't be supported.

**Pull request closed without merging**
