### PR TITLE
THRIFT-3706 : Implement protocol multiplexor in c_glib

### PR DESCRIPTION
**Pull request by gadLinux**
This patch implements protocol multiplexor for the client. For the server there's a need for a processor that currently we don't have. So a test of this can only be tested against other language that already has this in place. We did testing against Java. 

Example of use:

				/*
				 * We will use binary encoding
				 */
				ThriftBinaryProtocol *binary_protocol= g_object_new (THRIFT_TYPE_BINARY_PROTOCOL,
						"transport", manager->transport,
						NULL);

				/*
				 * FIXME Transport in the multiplexed should be got from binary_protocol
				 */
				ThriftMultiplexedProtocol *multiplexed_protocol= g_object_new (THRIFT_TYPE_MULTIPLEXED_PROTOCOL,
						"transport", manager->transport,
						"protocol", binary_protocol,
						"service-name", "MyService",
						NULL);

### CODE REVIEW

**Comment by nsuke** [comment]
@gadLinux could you rebase this to the current master ?

**Comment by gadLinux** [comment]
Sorry forget about this I screwed it up

**Comment by gadLinux** [comment]
I will redo it

**Comment by gadLinux** [comment]
Hi,

It's done in another pull request.

**Comment by gadLinux** [comment]
Please use this one. 
https://github.com/apache/thrift/pull/927

**Pull request closed without merging**
