### PR TITLE
THRIFT-5132 Warning in TSocket when using ssl connection

### PR DESCRIPTION
**Pull request by sveneld**
Warning in TSocket when using ssl connection

When you using ssl host in 

new TSocket('ssl://test.com') 

you will get a warning

PHP Warning: socket_import_stream(): cannot represent a stream of type tcp_socket/ssl as a Socket Descriptor in /usr/share/php/Thrift/Transport/TSocket.php on line 254

due to the bug https://bugs.php.net/bug.php?id=70939

### CODE REVIEW

**Comment by sveneld** [comment]
@Jens-G  is it possible to recieve some reaction on pull-request?

**Comment by Jens-G** [comment]
118 commits to merge? Are you sure you did the right thing?

> @Jens-G is it possible to recieve some reaction on pull-request?

Sorry didn't see that, so late response. We regularly look through open PRs and one of the first criterions is whether CI is "red" or "green". If it is green (i.e. all checks pass) then someone will sooner or later look at it. 

If there is no reaction on a green CI for say 10 days or so, you may politely ask and remind about the PR. 

If the CI is read, then first should be to try to fix the issues and/por force push to trigger CI again. Sometimes you may get false positives, unfortunately so if you are sure everything is correct, a simple rebase + force-push may be just enough.

**Comment by Jens-G** [comment]
But 118 commits to merge ... I'd say you should try a rebase first, only merging your changes, and squash them into one commit.

**Comment by sveneld** [comment]
@Jens-G  new pull request created https://github.com/apache/thrift/pull/2160

**Pull request closed without merging**
