### PR TITLE
THRIFT-5297: Improve TThreadPoolServer Handling of Incoming Connections

### PR DESCRIPTION
**Pull request by belugabehr**
- [X] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [X] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x ] Did you squash your changes to a single commit?  (not required, but preferred)
- [X] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [X] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by Jens-G** [comment]
@belugabehr There seem no objections from anyone. What about triggering the CI again and commit if all is green? 
@ java devs: Any comments on this change?

**Comment by belugabehr** [comment]
@Jens-G Thank you for your interest.  I believe there were some comment about moving the back-off functionality to the client code, which is not inappropriate, but I have not yet had the time to implement.

Happy to get this part in first if that's OK.

**Comment by belugabehr** [comment]
@Jens-G Any ideas on how to kick off the automated build/test suite?

**Comment by belugabehr** [comment]
OK.  Looks like there was a lag.  All good now.

I ran into some hardship recently trying to debug an application build on Thrift server.  I have some ideas for making it more debug-able, but need this in first and then can build on it.

**Comment by belugabehr** [comment]
@Jens-G Should be good to go now.  C++ failures only.

**Pull request closed without merging**
