### PR TITLE
THRIFT-5135: Compiler: Enable C++11 on OSX

### PR DESCRIPTION
**Pull request by janosvitok**
Fix Thrift compile CMAKE compilation by enabling C++11 standard.

- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, add ` [skip ci]` at the end of your pull request to free up build resources.

### CODE REVIEW

**Comment by janosvitok** [comment]
@Jens-G Does it make sense to add travis job to build compiler using cmake on OSX?

**Comment by janosvitok** [comment]
Appveyor failure: timeout during concurrency_test -- not related.

**Comment by emmenlau** [comment]
I think something else must be wrong. This PR should not be required.

See in https://github.com/apache/thrift/blob/dd63da19fad25ff8379f9505e626b16f45593e57/build/cmake/DefineCMakeDefaults.cmake#L66 there is c++11 enabled on all platforms. And its even respecting that you can overwrite the version from the command line, for example using:
```
cmake -DCMAKE_CXX_STANDARD=17 ... other options
```

**Comment by Jens-G** [comment]
Any news here?

**Comment by janosvitok** [comment]
I've checked this. The problem is that when running cmake on the whole tree, DefineCMakeDefaults.cmake is pulled in.
On the other hand, when running cmake just on compiler/cpp subtree, the relevant macro is not set.

See https://github.com/apache/thrift/blob/master/compiler/cpp/README.md#build-using-cmake that explicitly mentions running cmake from compiler/cpp

Summary: the issue here is lack of cmake documentation.

**Pull request closed without merging**
