### PR TITLE
Fix use closed(freed) connections

### PR DESCRIPTION
**Pull request by xiaosuo**
When failing to add tasks into the thread manager, we close the
corresponding connections, then set the flags of these connections,
which have been already freed.

### CODE REVIEW

**Comment by xiaosuo** [comment]
I had tried to find my password, but nothing was received. It seems that Jira doesn't work properly with gmail. Could you help me?

**Comment by xiaosuo** [comment]
@jeking3 you are correct. In fact, we had found this issue, and we should do such things at all the error path when notifying the io threads. I will address this issue in a separated patch.

At the same time, we should setIdle() before calling addTask(). Because the added task maybe expired and destroyed by other threads due to failing to notify IO threads, and the latter setIdle() may corrupt the memory.

**Comment by jeking3** [comment]
This patch as-is causes a counting error, so if you can amend this one with those changes we can get them all fixed together.

**Comment by jeking3** [comment]
@xiaosuo just a reminder, if you have additional fixes (it sounds like you do)

**Comment by xiaosuo** [comment]
@jeking3 Did you mean that we should fix all issues about the number of active processors in this patch instead of a separated one?

**Comment by jeking3** [comment]
If you have the fixes let's get them all in together.  The current fix is not complete and causes counting errors, which lead to - I don't know...

**Comment by xiaosuo** [comment]
I think this patch doesn't introduce any inconsistency. And the correctness of the number of active processors deserves another separated patch. We'd better not mix fixes into a huge patch.

BTW: Fixing the number of active processors may depend on my other patches. So I prefer to submit it after all my patches are merged.

**Comment by jeking3** [comment]
Please rebase this branch against upstream/master and force push to kick off a new build.  I would like to see the CI build pass (or get much closer than it is now) before merging.

**Comment by jeking3** [comment]
THRIFT-4160

**Pull request closed without merging**
