### PR TITLE
Fix typo for python 3 support

### PR DESCRIPTION
**Pull request by cfriedt**
`--with-py3` was not working as expected before, so I did a quick investigation and found there was a typo.

- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [x] If your change does not involve any code, add ` [skip ci]` at the end of your pull request to free up build resources.

### CODE REVIEW

**Comment by cfriedt** [comment]
I should note that the checks were not successful because of this

```
[00:01:05] Download of win_flex_bison-2.5.18.zip (954.72 KB) completed.
[00:01:08] Hashes match.
[00:01:08] Extracting C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\winflexbison3\2.5.18.20190508\win_flex_bison-2.5.18.zip to C:\ProgramData\chocolatey\lib\winflexbison3\tools...
[00:01:08] C:\ProgramData\chocolatey\lib\winflexbison3\tools
[00:01:09]  ShimGen has successfully created a shim for win_bison.exe
[00:01:09]  ShimGen has successfully created a shim for win_flex.exe
[00:01:09]  The install of winflexbison3 was successful.
[00:01:09]   Software installed to 'C:\ProgramData\chocolatey\lib\winflexbison3\tools'
[00:01:09] 
[00:01:09] Chocolatey installed 1/1 packages. 
[00:01:09]  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
[00:01:12] Error downloading remote file: One or more errors occurred.
[00:01:12] Inner Exception: Remote server returned 404: Not Found
```
Not because my change broke something.

**Comment by dcelasun** [comment]
Thanks for the PR!

**Comment by janosvitok** [comment]
@cfriedt would you describe in more detail what was the problem with --with-py3? Would you describe also the environment (OS, python distribution, version)?

It seems to me that your change broke CI (i.e. linux with /usr/bin/python = 2.x, /usr/bin/python3=3.x).  If I revert your change, CI is working again, but that breaks --with-py3.

I need to know about your problem so we can fix both problems ( and CI).

Thanks

**Comment by cfriedt** [comment]
@janosvitok  `--with-py3` is there to enable python 3 support.

Prior to this patch, `configure` was failing to detect python3 support and would fail even when explicitly passing `--with-py3`.

Upon inspection, it was pretty obvious that `configure` would only accept a Python 2 version when specifying `--with-py3`, which is not the desired behaviour. To me, it seemed very clearly to be a typo. I only have python3, since python2 is now deprecated, so it was quite obvious that there was a problem.

Have you looked at the diff?

**Comment by janosvitok** [comment]
What I see in docker ubuntu image is: with your patch python3 is not detected.
This is because /usr/bin/python returns Python 2.7.x and the rest is skipped.
In this case configure should check and find /usr/bin/python3 and/or /usr/bin/python3.6

What is your operating system and how did you install python so I can try to reproduce?

It is clear that there are two kinds of setup that are not properly handled:
1. both python 2 and 3 installed (the docker ubuntu case): /usr/bin/python is 2.x, /usr/bin/python3 is 3.x
2. only python 3 is installed (your case): both /usr/bin/python and /usr/bin/python3 are 3.x

Without your patch 1. is handled ok, and 2. not. With your patch vice versa.

**Comment by janosvitok** [comment]
What I see in docker ubuntu image is: with your patch python3 is not detected.
This is because /usr/bin/python returns Python 2.7.x and the rest is skipped.
In this case configure should check and find /usr/bin/python3 and/or /usr/bin/python3.6

What is your operating system and how did you install python so I can try to reproduce?

It is clear that there are two kinds of setup that are not properly handled:
1. both python 2 and 3 installed (the docker ubuntu case): /usr/bin/python is 2.x, /usr/bin/python3 is 3.x
2. only python 3 is installed (your case): both /usr/bin/python and /usr/bin/python3 are 3.x

Without your patch 1. is handled ok, and 2. not. With your patch vice versa.

**Comment by cfriedt** [comment]
I'm just using Ubuntu (bionic) in a docker container. After firing up the container, run
```
apt update
apt install python3
```
Install minimal dependencies of thrift (e.g. build-essential autoconf automake pkg-config libtool, flex, bison, git, etc). Then check out the sources and build.

**Comment by janosvitok** [comment]
@cfriedt: #2055 contains new version of the code. I made two if's: if $python is 2 then search for $python3; and if $python is 3 then $python3 = $python and have_py3="yes"

Now there's code that should always execute under python2... another can of worms :)

**Pull request merged**
