### PR TITLE
THRIFT-3200 JS and nodejs do not encode JSON protocol binary fields a…

### PR DESCRIPTION
**Pull request by nsuke**
…s base64

### CODE REVIEW

**Comment by bufferoverflow** [comment]
:+1:  great!

**Comment by beberg** [comment]
Great testing improvements, but it's still not base64

**Comment by beberg** [comment]
Sorry, to clarify btoa() was only added to IE in v10, so this isn't a fully portable implementation.

**Comment by bufferoverflow** [comment]
I think it is ok to not support IE < v10
This change needs to be committed base64 can be another step.
test integration done here is awesome!

**Comment by beberg** [comment]
Agree it should be commited, but leave behind a ticket for universal support.

**Comment by nsuke** [comment]
It seems that IE10 has btoa/atob and it was the first version.
http://caniuse.com/#feat=atob-btoa
https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/btoa

**Pull request closed without merging**
