### PR TITLE
THRIFT-4260: Add context as first arg for client method.

### PR DESCRIPTION
**Pull request by taozle**
Related: https://issues.apache.org/jira/browse/THRIFT-4260

### CODE REVIEW

**Comment by dcelasun** [comment]
Travis failures seem unrelated.

cc @Jens-G

**Comment by taozle** [comment]
@dcelasun @Jens-G PTAL

**Comment by dcelasun** [comment]
LGTM (once again, travis failure is unrelated)

**Comment by domino14** [comment]
Is this in the latest version of thrift? It seems that auto-generated code does not have `context` in its function signatures, but thrift itself requires them, so auto-generated code does not compile with the version of thrift that generated it!

**Comment by taozle** [comment]
You must use the generator compiled from the master branch.

**Pull request closed without merging**
