### PR TITLE
 THRIFT-4953: Missing Field Identifiers

### PR DESCRIPTION
**Pull request by dbcfd**
When identifiers are not specified, negative id will be converted to a valid
rust identifier.

This is building on the work in #1851, and could either replace it or be merged after.

- [X] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [X] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [X] Did you squash your changes to a single commit?  (not required, but preferred)
- [X] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, add ` [skip ci]` at the end of your pull request to free up build resources.

### CODE REVIEW

**Comment by allengeorge** [comment]
@dbcfd First, thank you for making this PR, and, sorry for the delay in getting back to you. I'll take a look in the next couple of days, but just wanted to let you know.

**Comment by allengeorge** [comment]
Looks like we have failures in multiple builds. At least _some_ look spurious, but some are more concerning. Rerunning build to try see what's up. @dbcfd

**Comment by allengeorge** [comment]
I can't seem to run the appveyor build from the console :( I may end up rebasing and repushing once we've made the travis build successful to trigger the appveyor build.

**Comment by Jens-G** [comment]
The JIRA ticket is still open?

**Comment by allengeorge** [comment]
My apologies :(

**Pull request merged**
