### PR TITLE
THRIFT-4147: Rust: protocol should accept transports with non-static …

### PR DESCRIPTION
**Pull request by sunchao**
…lifetime

### CODE REVIEW

**Comment by sunchao** [comment]
cc @allengeorge to take a look.

**Comment by allengeorge** [comment]
Will take a look today.

**Comment by allengeorge** [comment]
@Jens-G This looks good to me. Can it be merged?

**Comment by allengeorge** [comment]
Note that I've tested it against master, and all the rust tests and cross-tests pass.

**Pull request closed without merging**
