### PR TITLE
Node.js: Set/unset client seqid for json_protocol and compact_protocol

### PR DESCRIPTION
**Pull request by vh**
Like binary_protocol does.

### CODE REVIEW

**Comment by jeking3** [comment]
This change needs a Jira ticket; please see https://thrift.apache.org/docs/HowToContribute.  Also if you can rebase on master and push that will kick a new CI build; CI needs to pass (or failures easily explained) to merge.

**Comment by jeking3** [comment]
This change needs a Jira ticket; please see https://thrift.apache.org/docs/HowToContribute. Also if you can rebase on master and push that will kick a new CI build; CI needs to pass (or failures easily explained) to merge.

**Comment by jeking3** [comment]
@bananer is this worth pulling forward if it passes a build?

**Comment by bananer** [comment]
@jeking3 To be honest, I don't know why this is useful/necessary. I think there is no need for a seqid because the connection between request and response is handled through callbacks automatically.

**Comment by jeking3** [comment]
In general I want to make sure all clients send a seqid and all servers put that seqid in the result.  Without this we won't be able to have clients that can have multiple outstanding requests in the future.

**Comment by bforbis** [comment]
This should have updates added to it that were done in https://issues.apache.org/jira/browse/THRIFT-4480, otherwise the server will spam logs for every requests if they come from clients that send seqid = 0 (perl does this)

**Comment by jeking3** [comment]
Original author is not responsive and deleted his upstream branch/repo.  I am closing this.

**Pull request closed without merging**
