### PR TITLE
THRIFT-3500: Strings unicode py2

### PR DESCRIPTION
**Pull request by johnlockwood-wf**
As the test shows, this makes Thrift protocols treat Strings as unicode in Python 2 which is essentially equivalent as the str in Python 3. Indeed Python 3.5 now treats u"hello" as a str literal, just as Python 2 treats it as a unicode literal.

The python 2 standard lib contains the json package, that, when loading JSON, deserializes strings into unicode objects, where the TJSONProtocol deserializes them into utf-8 encoded bytes without this change.

https://issues.apache.org/jira/browse/THRIFT-3500

### CODE REVIEW

**Comment by nsuke** [comment]
In the current design, unicode in py2 is handled by -gen py:utf8strings compiler switch.
Does it cover your use case ?

**Comment by johnlockwood-wf** [comment]
I don't know, is there any documentation on what that option does? I'll just try it.

**Comment by johnlockwood-wf** [comment]
@nsuke, that option does appear to do the job when using the JSONProtocol.

**Comment by jeking3** [comment]
This pull request is being closed due to lack of activity.
You can re-open it after rebasing on the current master if you would like it to be reconsidered.

**Pull request closed without merging**
