### PR TITLE
THRIFT-5236 THttpTransport.cs still has bad timeout code

### PR DESCRIPTION
**Pull request by thomasbruggink**
Client: netstd

Allow connect timeout to be configurable.

### CODE REVIEW

**Comment by Jens-G** [comment]
Still? Wonder why it has not been done "properly" at the first time then.

**Comment by thomasbruggink** [comment]
It seems the implementation was lost when it was migrated from csharp, netcore to netstd. Since there is now only one implementation hopefully it will stay here.

**Comment by Jens-G** [comment]
Since https://dotnet.microsoft.com/download/dotnet does no longer list 2.0 as supported version I think it is safe to remove all netcore 2.0 specifics.

**Comment by thomasbruggink** [comment]
> Since https://dotnet.microsoft.com/download/dotnet does no longer list 2.0 as supported version I think it is safe to remove all netcore 2.0 specifics.

My original comment was written against an older master that didn't have net5.0 targets yet. Sorry for the confusion :bowing_man:

**Comment by Jens-G** [comment]
No confusion, 2.0 is still in the list of supported platforms. And there are several special cases to deal with it. I really meant it. Maybe a different PR, that's fine.

**Comment by Jens-G** [comment]
Thank you!

**Pull request closed without merging**
