### PR TITLE
THRIFT-5501 Remove Common Lisp support

### PR DESCRIPTION
**Pull request by Jens-G**
Client: cl
Patch: Jens Geyer

### CODE REVIEW

**Comment by m-g-r** [comment]
Hello Jens, why is the Common Lisp support removed? I am using it and was just surprised that it is suddenly removed.
From Berlin, Max

**Comment by Jens-G** [comment]
[THRIFT-5476 Deprecate and remove Common Lisp language bindings](https://issues.apache.org/jira/browse/THRIFT-5476)  due to the lack active  maintainers.

See also the [mailing list tread](http://mail-archives.apache.org/mod_mbox/thrift-dev/202110.mbox/%3C9014BF98D742484E8B04E052EEE8668B%40HAGGIS%3E).

[THRIFT-5501 Remove Common Lisp support](https://issues.apache.org/jira/browse/THRIFT-5501)

If there is some interest in reactivating CL, we're happy to do that **given there is at least one maintainer for it**.

**Comment by Jens-G** [comment]
The fine print is that we also had a lot of build issues with it and nobody to take care.
Since this is 100% FOSS, you are free to join and [start contributing at any time.](http://thrift.apache.org/docs/HowToContribute)

**Comment by m-g-r** [comment]
Hi, I currently just continue to use it. And the Common Lisp language backend seems to be quite complete, stable and generates efficient code. I use it to talk to Accumulo via the Accumulo Proxy and that allows for high ingestion rates as I have described in this article "Almost 600,000 entries per second from Lisp to Accumulo" at https://observablehq.com/@m-g-r/almost-600000-entries-per-second-from-lisp-to-accumulo As written in section "Comparison", it seems safe to argue that in this test we achieve a comparable raw ingestion performance to similar measurements of the ingestion rate to Apache Accumulo.

I was basically frankly surprised that you just remove such a complete language backend given that seems this seems to be the very thing Apache Thrift is about: a "language-independent software stack" allowing "programs written in different programming languages" to communicate with each other.

Admittingly, I just use James' `de.setf.thrift` at https://github.com/lisp/de.setf.thrift directly and have just thrift via the Ubuntu package thrift-compiler installed to generate the lisp code from the thrift definition file...

Hm, THRIFT-5410 “CL build broken: Component :NET.DIDIERVERNA.CLON.TERMIO not found” is according to your email https://www.mail-archive.com/dev@thrift.apache.org/msg50775.html just a test not running, right? In file "thrift/src/test/cl/make-test-server.lisp" and that breaks your build system, or rather the continuous integration service? That test uses Didier's `clon` to parse commond-line options in a standalone application `TestClient`.

Let me see if I can reproduce that. Currently looking at make running to build thrift which seems to take a while.

Cheers, Max

**Comment by m-g-r** [comment]
Hi @Jens-G,

I've made a workaround to alleviate THRIFT-5410. The problem is that the system :NET.DIDIERVERNA.CLON was subdivided in a way that the version of the package loader ASDF that is used here cannot find. The workaround locates that subsystem clon.termio explicitly.

You'll find the changes in https://github.com/m-g-r/thrift/tree/THRIFT-5410 (Of course, I had to revert the commit ["THRIFT-5501 Remove Common Lisp support"](https://github.com/apache/thrift/commit/5fecc439f5244fd8585cb053877074dd1d170c30) first.)

I have run the checks and all seems to work now. I have only tested with cl support. That is, I deactivated the other language bindings that would otherwise run and take quite a bit of time, by running configure as:
```
./configure --with-ruby=no --with-php=no --with-nodejs=no --with-cpp=no --with-python=no
```
Mind you, this problem was just about running tests. The Common Lisp Thrift backend itself seems to be really stable. I am using it for months now.

Are there any other problems? As I have built it on one of my systems now, I can also look for other things if it only takes an hour or two.

Cheers, Max

**Comment by m-g-r** [comment]
I just did. See above. I have been working on an lisp library to make working with Accumulo via Accumulo Proxy nicer. I'd like to commit that to the Accumulo Proxy project but that makes only sense if Common Lisp is still supported by Thirft.

**Comment by Jens-G** [comment]
Can't find it under https://github.com/apache/thrift/pulls ?

**Comment by m-g-r** [comment]
It was not up to date as per the latest version of the 'master' branch. Updated now by reverting another change that was done in the meantime, see https://github.com/apache/thrift/pull/2646.

Cheers, Max

**Pull request merged**
