### PR TITLE
THRIFT-5346: Add prePocess postProcess and errorProcess to Server Con…

### PR DESCRIPTION
**Pull request by belugabehr**
…text

  

- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [ ] Did you squash your changes to a single commit?  (not required, but preferred)
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by Jens-G** [comment]
Is this a breaking change?

**Comment by belugabehr** [comment]
@Jens-G Yes.  Renamed one of the methods and added a few more to an Interface, so anyone using this interface will have to updated.  I don't know how popular feature it is, from my reading, seems like it was put in for Hive some time ago.

**Comment by Jens-G** [comment]
I'm a bit hesitant about introducing a last minute breaking change. Also CI fails.

**Comment by belugabehr** [comment]
@Jens-G No worries.  I  was able to work around it well enough.  Not a blocker.  Thanks.

**Comment by Jens-G** [comment]
Any news here?

**Pull request closed without merging**
