### PR TITLE
THRIFT-5109: Misc CMake build improvements

### PR DESCRIPTION
**Pull request by emmenlau**
Patch: Mario Emmenlauer

This closes #2026
This closes #2025
This closes #2021

- [x] https://issues.apache.org/jira/browse/THRIFT-5109
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [x] If your change does not involve any code, add ` [skip ci]` at the end of your pull request to free up build resources.

### CODE REVIEW

**Comment by jeking3** [comment]
Moving towards one build system (cmake) is a great effort, it's nice to see this happening in some capacity.  Unfortunately when builds break... merging is hard. :)

**Comment by emmenlau** [comment]
> Unfortunately when builds break... merging is hard. :)

Haha yes! I was actually hoping [you could help with the Gruntfile](https://issues.apache.org/jira/browse/THRIFT-5109?focusedCommentId=17083999&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17083999)?

The "problem" now is not that the CMake build itself would be broken. The problem is that the Javascript build in autotools was not used on MSVC before, whereas in CMake I have now enabled Javascript on MSVC. And it fails, probably never worked.

This could and should be split off into a separate issue, unless you (or someone else) could fix the Javascript build?

**Comment by emmenlau** [comment]
The rest of this PR should be fine and should have worked from the start. The failing Javascript could just be disabled on AppVeyor.

**Comment by janosvitok** [comment]
I was going to suggest the same thing, but was distracted and didn't get back to it.

Since JS issue is unrelated to cmake (the issue is that JS can't be compiled on windows), one solution is to disable JS build on windows, and make another issue for JS.

**Comment by emmenlau** [comment]
I've found a small improvement where the Javascript target actually depends on the target that copies the compiler into the source tree, not on the build of the compiler. This ensures that if the compiler is *not* built, it will still be copied.

If the CI is now successful, this should be ready for review / merge.

**Comment by emmenlau** [comment]
There seems to be an unrelated issue in https://travis-ci.org/github/apache/thrift/jobs/677163097. Should I re-trigger the builds and tests?

**Comment by emmenlau** [comment]
Re-triggered build with a rebase on latest master, to fix random error in Travis CI.

**Comment by emmenlau** [comment]
:-( Another random error in the CI. Can this be merged anyways?

**Comment by emmenlau** [comment]
Ready for review.

**Comment by Jens-G** [comment]
@janosvitok comments from your side?

**Pull request closed without merging**
