### PR TITLE
Github Actions: Remove --disable-tests

### PR DESCRIPTION
**Pull request by fishy**
With --disable-tests, for example for Go the `make check` under `lib/go`
would only run unit tests under `lib/go/thrift` but not the unit tests
under `lib/go/test`.

Also some changes in lib/go/test/fuzz/Makefile.am so it works in both go
1.20 and 1.21 (The current state breaks in 1.21 but because of
`--disable-tests` we never noticed that).

### CODE REVIEW

**Comment by fishy** [comment]
cc @catenacyber this changes removes `go.mod`/`go.sum` under `lib/go/test/fuzz`, which _might_ affect how oss-fuzz runs. based on the [previous PR](https://github.com/apache/thrift/pull/2724) the impact might be minimal but just want to make sure :)

it would be great if oss-fuzz can use go's native fuzz implementation instead.

**Review by dcelasun — APPROVED** [review]

**Comment by catenacyber** [comment]
> this changes removes `go.mod`/`go.sum` under `lib/go/test/fuzz` (they are now generated on-the-fly by `make check` now), which _might_ affect how oss-fuzz runs. based on the [previous PR](https://github.com/apache/thrift/pull/2724) the impact might be minimal but just want to make sure :)

Fails with oss-fuzz
`python3 infra/helper.py build_fuzzers thrift` with patched Dockerfile
```
-RUN git clone --depth 1 https://github.com/apache/thrift
+RUN git clone --depth 1 --branch go-run-tests https://github.com/fishy/thrift
```

> it would be great if oss-fuzz can use go's native fuzz implementation instead.

@AdamKorcz this is now the case, right ?
See https://google.github.io/oss-fuzz/getting-started/new-project-guide/go-lang/#native-go-fuzzing-support

**Comment by AdamKorcz** [comment]
> @AdamKorcz this is now the case, right ?
See https://google.github.io/oss-fuzz/getting-started/new-project-guide/go-lang/#native-go-fuzzing-support

Yes

**Review by Jimexist — APPROVED** [review]

**Comment by catenacyber** [comment]
> catenacyber thanks, can you try again with the newest version of this branch?

Still failing

First `make` is failing with `make[4]: *** No rule to make target 'src/thrift/numeric_cast.h', needed by 'all-am'.  Stop.`

Then golang is failing with logs
```
go: finding module for package github.com/apache/thrift/lib/go/test/fuzz/gen-go/tutorial
go: finding module for package github.com/apache/thrift/lib/go/test/fuzz/gen-go/shared
go: github.com/apache/thrift/lib/go/test/fuzz imports
	github.com/apache/thrift/lib/go/test/fuzz/gen-go/shared: module github.com/apache/thrift/lib/go/test@latest found (v0.0.0-20231127082722-8a6bcc76f30b), but does not contain package github.com/apache/thrift/lib/go/test/fuzz/gen-go/shared
go: github.com/apache/thrift/lib/go/test/fuzz imports
	github.com/apache/thrift/lib/go/test/fuzz/gen-go/tutorial: module github.com/apache/thrift/lib/go/test@latest found (v0.0.0-20231127082722-8a6bcc76f30b), but does not contain package github.com/apache/thrift/lib/go/test/fuzz/gen-go/tutorial
github.com/apache/thrift/lib/go/test/fuzz
github.com/apache/thrift/lib/go/test/fuzz
Running go-fuzz -tags gofuzz -func Fuzz -o fuzz_go_tutorial.a .
fuzz.go:30:2: no required module provides package github.com/apache/thrift/lib/go/test/fuzz/gen-go/shared; to add it:
	go get github.com/apache/thrift/lib/go/test/fuzz/gen-go/shared
fuzz.go:31:2: no required module provides package github.com/apache/thrift/lib/go/test/fuzz/gen-go/tutorial; to add it:
	go get github.com/apache/thrift/lib/go/test/fuzz/gen-go/tutorial
```

**Comment by fishy** [comment]
@catenacyber hmm the make failing is weird, certainly not related to this change.

for the rest, can you point me to the script actually run by oss-fuzz? I think some slight modifications are needed. if you look at the changes to files under `lib/go/test/fuzz` in this PR, we no longer generate individual go modules (run `go mod init` under the two directories generated by thrift compiler, and changed the import path in `fuzz.go`. we also changed the thrift compiler args to make it work.

**Comment by catenacyber** [comment]
https://github.com/google/oss-fuzz/blob/master/projects/thrift/build.sh

Let me know id it needs some changes

**Comment by fishy** [comment]
> https://github.com/google/oss-fuzz/blob/master/projects/thrift/build.sh
> 
> Let me know id it needs some changes

@catenacyber: 

We would need to change line 32 into:

```
thrift -r --gen go:package_prefix=github.com/apache/thrift/lib/go/test/fuzz/gen-go/ ../../../../tutorial/tutorial.thrift
```

and then remove lines 33-34 (line 35 probably can also be removed, but I think leaving it would also be harmless)

**Comment by fishy** [comment]
@catenacyber I created https://github.com/google/oss-fuzz/pull/11296 on oss-fuzz.

**Comment by Jens-G** [comment]
That was added in 779deab, the file was removed in 49e4cea but seems not the reference in the *.am file. I would say throw it out.

**Comment by catenacyber** [comment]
> That was added in [6e9cbbd](https://github.com/apache/thrift/commit/6e9cbbd059b00741c886b252cc63d325e4d86e22) and [779deab](https://github.com/apache/thrift/commit/779deabf0e1fdefe4f6340546181ac9d81fcf670). The file was then removed in [49e4cea](https://github.com/apache/thrift/commit/49e4cea002fed0133b4cd3baf88c73787b1f1907) but as it seems not the reference in the *.am file. So I would say throw it out.

Is anyone taking care of this ?

**Comment by fishy** [comment]
> > That was added in [6e9cbbd](https://github.com/apache/thrift/commit/6e9cbbd059b00741c886b252cc63d325e4d86e22) and [779deab](https://github.com/apache/thrift/commit/779deabf0e1fdefe4f6340546181ac9d81fcf670). The file was then removed in [49e4cea](https://github.com/apache/thrift/commit/49e4cea002fed0133b4cd3baf88c73787b1f1907) but as it seems not the reference in the *.am file. So I would say throw it out.
> 
> Is anyone taking care of this ?

https://github.com/apache/thrift/pull/2899

**Pull request merged**
