### PR TITLE
THRIFT-5399: Fix socket leak in abnormal situation(c_glib)

### PR DESCRIPTION
**Pull request by lm2048**
- [x] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [x] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

### CODE REVIEW

**Comment by lm2048** [comment]
Client: c_glib

**Comment by Jens-G** [comment]
If anybody from the c_glib people could do a review I would be happy to merge this.

**Review by feral-diana — APPROVED** [review]

**Comment by feral-diana** [comment]
AppVeyor build failed because of outdated cmake. Fixed in https://issues.apache.org/jira/browse/THRIFT-5394 . How to restart it?

**Review by ulidtko — APPROVED** [review]
LOTM

**Pull request merged**
