### PR TITLE
fix compile error(Windows7 x64) : there is no lib\cpp\src\thrift\Thri…

### PR DESCRIPTION
**Pull request by lizhenghn123**
* fix compile error(Windows7 x64) : there is no lib\cpp\src\thrift\Thrift.cpp file.

### CODE REVIEW

**Comment by kcris** [comment]
seems incomplete, until more files are added to the vcxproj, see pull request #745

**Comment by lizhenghn123** [comment]
add TProtocol.cpp and TOutput.cpp in libthrift.vcxproj

**Comment by kcris** [comment]
I did. I have both removed Thrift.cpp from the project file, and also added TProtocol.cpp and TOutput.cpp (see pull request #745, was merged already).
So this pr (#739) should be closed I think.

**Comment by lizhenghn123** [comment]
Thanks!

**Pull request closed without merging**
