### PR TITLE
THRIFT-4583: Switch to rebar3

### PR DESCRIPTION
**Pull request by kpy3**
Client: erl

  

- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [x] Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?  (not required for trivial changes)
- [x] Did you squash your changes to a single commit?
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"

### CODE REVIEW

**Comment by jeking3** [comment]
Seeing a lot of different build failures... I'll try to work on it.

**Comment by kpy3** [comment]
@jeking3 Hm, looks like the problem in build itself, not in my changes?

**Comment by jeking3** [comment]
I agree, but we like to get clean builds before we merge stuff, so we need to wait for the golang issue to be resolved by @dcelasun and then we'll ask folks to rebase things.

**Comment by kpy3** [comment]
I see, thanks for response.

**Comment by jeking3** [comment]
The CI issues have been resolved so I would suggest rebasing on master to get a clean run.

**Comment by kpy3** [comment]
@jeking3 Rebased, looks good

**Comment by jeking3** [comment]
Sadly, this actually removed erlang from all our CI builds, since the standard Ubuntu Bionic erlang installation doesn't include rebar3.  I blame myself for not actually checking any of the build logs.  I'm working to fix it.

**Pull request merged**
